:PROPERTIES:
:ID:       84c5b566-23ff-4036-9f58-8b3fcbb1b8b1
:END:
#+title:Serotonin, Anxiety and Depression


Serotonin is a molecule used in the bodies of, as far as I'm aware, all animals.
It's used extensively in the human digestive system, but what makes it interesting for me to talk about is what it does in the brain.
Serotonin-based signaling is known to play a role in a variety of psychiatric conditions, especially anxiety and depression.
The most common antidepressants are called Selective Serotonin Reuptake Inhibitors (SSRIs), which act on serotonin-based signals.

You may have heard the idea that depression is due to a deficit of serotonin in the brain, and that SSRIs correct this defecit.
In truth the role of serotonin is much more complicated and much less well understood.
SSRIs clearly [[https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(17)32802-7/fulltext][do help]] with depression, but not for everyone, and sometimes one SSRI will work for someone while a different one doesn't.
Other medications which seem to have no significant effect on serotonin are also [[https://www.nature.com/articles/mp2017255][effective]] in many cases.

I want to take a deep dive into the role that serotonin plays in anxiety and depression, and go over some ideas regarding why they work (when they do).
Want to come with?

Ok, I say a deep dive. There is so much on this topic and so little consensus that an actual deep dive would take a whole career.
Keep in mind that I am not specialized in the study of serotonin, or anxiety, or depression, or pharmacology.

I'll organize this in a series of posts, each regarding one hypothesized or apparent role of serotonin anxiety or depression.
At the end of each post I'll put a little summary of the main points you need to grasp to carry on to the subsequent posts.

  - [[id:c924678f-5230-48d7-85d7-bf7413e5b2c8][neurotransmission-of-serotonin]]
  - [[id:9c8961f2-4dbd-4dc9-9cd5-f498abc8afaa][the-serotonin-deficiency-theory]]
  - [[id:02504069-e1e7-43c8-a746-43ed27a2f807][serotonin-and-heplessness]]  

# * SSRIs and SERT

# ** SERT expression

# ** other effects on the body

# * 5HT1A: reducing serotonin activity


# * 5HT2A:

# ** check wikipedia again

# * BDNF

# * Other possibilits.


# ** any one DRN serotoninergic pathway will inhibit other DRN pathways, is there a competitive regeime there?

# ** revisit montcrieff, she had something about reducing some receptor density?

