:PROPERTIES:
:ID:       73805a16-a739-4a75-b0b2-2414beb5319f
:END:
#+title: m-a-d

A fairytale to explain mutually assured destruction to children



# TODO: this dry tone aint for children, simplify your language!

A mad wizard named Mads once created a powerful spell.
The spell would cause the person it is cast on to slowly waste away and die over the course of one day and one night.
Years later, two of Mads' students who had both mastered the spell had a disagreement.

Their names were Sofiette and Nathoniel.
Each student believed they were the better student, and should succeed Mads as head of their order.
They both became worried that the other would try to kill them.
"If you cast any spell at me, I will cast the curse of death on you", said Sofiette.
"If so much as a spark comes my way, I will case the curse of death on you", said Nathoniel.

Yet Sofiette remained fearful - what if Natoniel was foolish and cast the spell anyway?
Nathoniel worried, what if Sofiette cast the spell without him noticing on time, so that he would be too weak to cast back.
And so they watched each other closely, death on the tip of their tongue in case they attacked.
But any agression they showed could mean both their deaths, and so they did not cast magic on each other.

Their rivalry could not end in truce however.
Sofiette bullied Nathoniel's friends, and Nathoniel bullied Sofiette's friends.
Each hoped to drive the other's friends away, and so reduce their power.
Fearing for their friends, each said to the other: "If you curse my friends to death, I will curse you".

Years passed in fearful misery, until one day, old and exhausted, Sofiette and Natoniel wished to end their horror.
"I have said that if you curse me to death, then I will do the same. What I haven't said is that if you don't curse me, I won't curse you" said Sofiette.
"All these years we feared for our lives. Let us put an end to it. I will not curse you to death." said Nathoniel.

They did not fully resolve their differences, and their students are bitter rivals to this day.
But they did live somewhat happily for many years after.







