:PROPERTIES:
:ID:       245d134a-80ac-4d13-a899-b52465bb36aa
:END:
#+title: tremble-and-zemble

The shadow of the huge monster approaches the door, and as you accept your fate, you see the most horrifying thing in the doorway. It walks over to you, opens its big mouth and ... "Have you seen my keys?".

* part 1


How is it forming those words? Its gaping maw opens and the words simply roll out, the eyes staring blankly.
Zemble blinks. The creature blinks.

Blink.

Blink.

The phrase was a question, but the tone was entirely flat. 

"I could have sworn I left them on the cupboard next to the wardrobe".

Zemble chanced a look around the room, barren stone and iron, crates and barrels. Certainly no wardrobe or similar furniture.
The creature wasn't wearing any clothes, why would it even need a wardrobe?

"Um..., no I haven't seen your keys."

The mouth closes, the eyes stare at some space above Zemble's head.

Blink.

Blink.

Blink.

The eyes snap to look him in the face, the monster trembles.
Its eyes snap back upwards, and the maw opens again, revealing rows of tiny teeth and a throat zemble could crawl through.

"Nice weather we're having."

Maybe the storm Zemble left behind is nice weather to a beastie like this, not that its likely ever been aboveground.
The creature uses a woman's voice, clear and pleasant but void of intonation.
Zemble was all too ready to cleave this horror, but curiosity overcomes fear.
After all, curiosity brought him here.

"Sure... would you like to go outside?"

Blink.

Blink.

Blink.

"let me just get my keys."

The monster turns, lumbers to the other end of the room, gestures vaguely at the wall.

Turned at a slight angle, Zemble sees the eyes moving again.

Blink.

Blink.

Blink Blink.


The creature turns and wanders back to Zemble. Is that hesitation in its step?

"Let's go outside".

Zemble steps aside and gestures for the creature to walk by him.

Blink.

Blink.

Blink.

"Right this way, friend".

Blink.

Blink.

"This way.", echoes the cavernous maw.

"To go outside. You want to go outside?".

"This way. This way."

Blink.

Blink.

"This way?"

Intoned like a question.

"Yes, this way. Here, I'll lead."

And so Zemble leads the way out.

* part 2


<!-- TODO this is overexplaining -->
Controlling his breathing to contain his fear at having the monster behind him, Zemble takes a moment to examine possibilities.
Perhaps one of the biomancer's creations, it has some markers of artificial life.
Zemble glances behind, the eyes are not looking where it is going, still staring blankly upwards.
A little experiment is in order.
Zemble climbs over a barrel, and looks back as he moves on to see what the creature does.
It mimics his climbing motion without looking down at all.
All right then.


The ruined castle sits on a barren peak among forested hills.
Into the storm emerges Zemble with the hulking monstrosity.
<!-- TODO: italics -->
I can't very well lead her back to camp, not if I don't know what she's after; Zemble thinks.
Ah dear, the voice alone is leading him to gender the thing.
Might as well give her a name now, does she seem like a Lucy?
She does not seem like a Lucy.

"What should I call you?" asks Zemble.

Blink.

Blink.

"My name is Zemble, it's nice to meet you." says Zemble, as pleasantly as he can.

"Nice to meet you Zemble". 

"What is your name?'

She shudders.

"Why were you down there?"

Blink.

Blink.

Blink.

Shudder.

"Is there anything you want?"

Shudder.

Shudder.

Blink.

The creature uncurls into its full height, easily three meters, the maw opens and from it emerges a despairing wail.


Could a creature construct such a sound? Or is she copying something she heard before? Does she know what it means? 
She wails on.
Zemble shelters under a nearby eave, afraid to act, afraid to leave her unsupervised.
Only some minutes later, a crash of nearby thunder interrupts her, and she shrinks to the curled two meter shape Zemble found her in.

Shudder.

Shudder.

Tremble.


"I will give you a name." Says Zemble. "Your name is Tremble. Isn't that fun? Zemble and Tremble."

"Hello, my name is Tremble." Tremble says flatly.

It's a terrible name thinks Zemble, but it's not like she'll care.
Certainly a better fit than Lucy.

"Can you wait here for me, Tremble?"

Blink.

"Wait." says Tremble, and all tension leaves her body, and she rests her limbs on the ground.

Zemble has no idea how well she can stand the cold and rain, so he had better hurry.


* part 3


Zemble rushes to the camp and fetches Serrandi.

"Where are we going in such a hurry?" Serrendi asks.

"Found a Bioautomaton, I think. I'm hoping you might know what's up with this one."

"Odd one is it?"

"I think she's having an existential crisis or something..."

"She?"

"you'll see -er. Hear what I mean".

"What?"

"No more talking, running".

And they ran.


* part 4


"Hello Tremble, this is my friend Serrandi".

"Done waiting." says Tremble, standing up again.

Blink.

Blink.

Serrandi gapes and Zemble places a hand on her back as she steps away.

"My name is Tremble, it is nice to meet you."

"Ana's voice. That's Ana's voice. Oh Ana what did you do?"

"Do you know Ana, Tremble? Anamit?" Asks Zemble.

"Mistress Anamit. Mistress Anamit?".

"Ana made you. What did she make you for?" Serrandi asks.

Shudder.

"Uh oh Serra, I think you've done it now"

Shudder. 

Uncurl. 

Wail.



Until the next crash of thunder, Serrandi blocked her ears and cried.
Tremble curls back up.

"...Ana's voice. Oh that sound breaks my heart".

"Do you think Tremble know what that sound means? Is Tremble in pain?"

"Tell me how you found Tremble."

"I'll tell you, inside. Come on Tremble, come inside."

Once back underground, Zemble lights a fire from the dry wood of a shattered barrel, and as tremble sits staring at the ceiling he tells Serrandi the events so far.


"Tremble must have been alone here for four hundred years".

"How could she have stayed alive?".

"Ana didn't give any of her creations a digestive system - had them all using ambient magic.
It's why she picked this place for her castle."

"And then what about my question? Is Tremble in pain?"

"I have a hunch. She follows your requests without much issue, but wails when you ask her purpose."

"Anamit would've made her for a reason. Action requires purpose."

"I remember Ana was against the idea that this applies to nonsentient creatures. I always thought she was onto something, look at non-animated life. They still act in response to the world - flowers turning to the sun and all. I don't think anyone would say they have purpose."

"Flowers have the purpose of growing and reproducing, they just aren't aware of that purpose".

Serrandi shoots Zemble an angry look.

"I thought you'd know better than that. Survival is not purpose, survival simply is. Purpose is a conscious construct".

"I'm not sure."

"Psychomancers distinguish betweeen habitual and purposeful behavior. In that sense, you could absolutely have an organism which acts without purpose."

"Certainly in an artifical lifeform that habit would be crafted to a purpose?".

"Not the lifeform's purpose though. Just the creator's."

"Fine. I don't really care either way. What about this hunch of yours?"

"I think Ana made Tremble to see if you could have an agent define its own habits without sentience or preassigned purpose".

"Without sentience?"

"Of course, Ana would never experiment with sentience - she had a heart you know."

"The best psychomancers today don't know how to guarantee nonsentience. How would Ana?"

"Yeah, there's the problem I guess. Ana thought she had that figured out. Looking at Tremble it's hard to say she was right."

They were quiet for a long time.


"You know those eyes are blind?"

"Yeah. Probably uses a magical sense. Can probably see every tiny detail from here to the lesser rivers. Ana was good with those. Normally a creature has to direct its senses to an extent, at least if the senses are complex enough. Magical senses can cut through a lot of that, give the direct sense of objects. Probably makes it easier to navigate without purpose".

"Sees everything, but has no reason to make sense of it. Explains the mimicry - acting out human conversations without understanding them".

"mimicry... when do you think she heard Ana scream like that?"

"Did Ana suffer melancholy, or anything like that?"

"Yeah, her wrestling with purpose had something to do with that I think."

"Maybe that explains why Tremble mimics the wail when the question is brought up."

Until the storm passed, the rest of the day was spent in silence.

With the sun shining outside, Serrandi speaks to Tremble.

"Come with us, Tremble. Your purpose is to help us understand you. Is that ok?"

"Ok?" Shudder. "Ok?"

"It's ok."

"Ok."






