:PROPERTIES:
:ID:       52db35dc-ee22-4ec0-816d-8eed5058fc40
:END:
#+title: the-soundtrack-of-the-apocalypse
What is the soundtrack of the Apocalypse?


* Burn


five hundred thousand years, one thousand conquered apocalypses.
See here, this is a fairly optimistic story.
Any coming thing could crush our potenial, some of them nearly will.
Make no mistake, each near-miss was a catastrophe, but a recoverable one.

One thousand an one is the charm aparrently, for earth that is.
By now we've spread throughout the stars right? 
Some of us heading to deep space.
I'd like to think that some of us are still in reach, able to help out refugees.
Mars perhaps? Europa?

On earth, relaxing just outside a building covered in greenery, A woman listens to a song.
She watches the sky, and hums along to a verse:

going down
burn for me

sky and ground
lost to greed
when all we need
is this


She's comforted by inevitability, accepted her fate months ago.
All she feels now is attentive curiosity, a calm anticipation.
The song was written recently, it spread throughout the globe, and was soon broadcast to the stars.
This song was made on earth, forged by the circumstances of its end.
In its death, earth and everyone on it will live forever.
A celebration and a warning, gratitude and mourning.
Mourning of the best kind is truly celebrating; a nostalgic catharsis.
Music which captured that provided comfort for those who remained.
Somehow I imagine many did, though I don't know why.

The woman lives this last moment fully, immersed in the sound, the sight of the world around her.
Music softly drifting from her radio as a warm breeze blows through the afternoon air.
What a lovely day, what a lovely moment to be one's last.
Tears at the beauty of what has been, then the world changes and she briefly laments. 

Even this is beautiful.
Then there is nothing.


I wish I could guess the nature of this doom: I imagine it would be as unfathomable to us as climate change and nuclear warfare to neolithic hunter-gatherers.
By then, I do believe we have mastered ourselves well enough to soothe our way through any circumstance; and endure the greatest calamity with a positive attitude.
To understand the effects and role of art, how our minds interact with our environments.
How can we best experience not just pleasure, but life as a whole?
Feeling fulfillment with all emotions and being grateful for each experience.

