:PROPERTIES:
:ID:       bb9e7c86-d383-4beb-a0da-77e180c4023a
:END:
#+title:Fifteen years of martial arts with dyspraxia.


[[id:2a4d5c06-28a1-4492-ae3c-1164a1826c8a][Dyspraxia]] is a learning disorder in which (among other things) motor learning and spatial reasoning are impaired.
Exercise is important for everyone, but for people with dyspraxia it is arguably more important.
It is also more frustrating, because we are almost always bad at it.
I'd like to tell my story of training in martial arts for fifteen years and the difficulties I've faced as a consequence.
I'd like to warn you that this one is likely to be on the self-indulgent side.
It's mostly to organize my thoughts and review the strategies I've used to keep training.
Hopefully I can come up with some reccomendations on how to deal with that, but that'd be a bonus.

At all points in my life I have practiced some kind of sport.
As a child I did this reluctantly, until I took and interest in martial arts at age 14.
I started at a karate dojo.

This was a school with a very traditionalist approach: we repeatedly practiced techniques on the air, adhering rigidly to a specific way of executing them.
This was mixed in with strength training, but the centerpiece of all training was something called a Kata.
Kata are a sequence of movements to memorize and perform over and over until they are perfected.
Kata show up in most japanese martial arts - though in judo, jujitsu and weapon-based arts they are done with a partner.
In Karate they are done alone, your own mind your only training partner.

One of the less obvious handicaps of dyspraxia is difficulty with sequencing.
When a number of steps need to be executed in a particular order, people with dyspraxia are more likely to mix up the order or forget a step.
It will also take them longer to learn a new sequence, and they need to practice it more consistently to maintain it.
As a child, I often put my backpack on my back, before putting on my jacket over my bag: and persisted in this mistake for years (to the bewilderment of my parents).
If I was lucky I at least had my lunchbox in my bag and my shoes already on, but from time to time I'd be straining reach my shoelaces in a jacket overstreched by a backpack, only to take jacket and bag off so I could get the lunchbox in.
I wasn't let out the door until I had things the right way around, luckily.

I had never been so diligent with any other sport as I was with karate.
I practiced outside of the dojo, doing kata in the garden, I missed social events to attend class, I started doing pushups and situps at home.
Why did karate motivate me more than other sports?
Partly because it (at least in theory) is about fighting, and fighting is cool.
Partly it was because I seemed to be good at it.
I find that for most people I speak to, 'becoming good' is a big part of the pleasure they get from sports.

When it came to kata, other children easily memorized them and then got too bored to put much effort into perfecting the techniques.
Maybe because the memorization was more of a challenge, I remained engaged where they faltered.
I advanced through the grades at doubled speed, yellow-orange-green-blue-purple belts flew by.
Shotokan Karate has three ranks of brown belt before black, sankyu, nikyu, ikkyu.
Sankyu-nikyu I slowed down to a normal rate, and I remained ikkyu three times as long as the average student.
I wasn't being undervalued, I simply wasn't getting any better.
I was getting kata mixed up, and for each new one I learned I began to struggle with an old one.

I wonder if I had reached my limit?
The thing you readers should understand about a black belt is that it is not a rank indicating mastery.
A black belt indicates a solid grasp of the basics: a minimum level of competence.
A high school degree, not a masters'.
Is that out of reach for me?
Would I eventually have started improving again if I'd just kept training consistently?
Was my reduced enthusiasm a result of my stagnant progress, or its cause?
I don't have the answers to these questions.


Any readers who are into martial arts can probably guess what happened when I went to try out other martial arts when I arrived at university.
I quickly learned that not only had I not learned a thing about fighting, but the way I had learned to move was the direct opposite of how you should move in a fight.
Well, I've softened my stance on that - traditional karate movements are the opposite of what you want to do in a striking exchange, but make some sense in a wrestling, clinching, handfighting context (a topic for another time).
Either way, it turns out that to actually get good at fighting people, you need to practice with a partner who is fighting back at least a little.
Who could have guessed?
Like so many young martial artists I viewed the practically useless skill of hand-to-hand fighting as very important, so continuing to train as I had was not an option.
Karate gave me many things - a stronger physique, an immeasurably better control of my body, and the ability to easily copy movements I see others do.
But the most valuable thing it gave me was a newfound self-skepticism: If I could be so completely convinced that traditional karate movements are good striking then I could clearly be convinced of more consequential untruths too.

So I was bad at fighting - and I could easily blame it on my previous training.
So no problem then - so what if I'm bad?
I've just been training wrong and if I train right, I'll get good.
Right?


* part 2

I did a little point karate, a little aikido, a little taekwondo, a bit of boxing and kickboxing.
I tried to crosstrain taekwondo and kickboxing for a while, but the habits that each was trying to teach me conflicted with the other.
I'd default to a staggered stance, power foot back, as suited me in kickboxing: but in taekwondo I'd be told off for not taking a side-on stance.
In kickboxing no one told me off for breaking convention and taking a side-on stance, instead they simply kicked my defenseless lead leg.
I decided I trusted the latter form of communication more, and dropped taekwondo to focus on kickboxing.

The simplicity of kickboxing was refreshing and astounding to me.
Shotokan is one of the simplest styles of karate, but even so had ten or so different blocks, seven or so stances, seven varieties of kick with several variations, and a wide variety of strikes using different parts of the arm and hand.
In kickboxing in contrast we were taught three basic punches, two basic kicks. 
Defense was fairly straightforward - evade, parry, or cover up.
Defend your upper body with your arms, your lower body with your legs.
Oh and above all, keep your hands up.

In karate we were taught to always, always pull one hand to your hip while striking with the other hand.
In kickboxing we were taught to always keep any hand that isn't striking glued to your head, your last and often only line of defense against counterstrikes and combinations.
You're reminded of it frequently by your sparring partners: you get hit, and they tap their gloves to their head to illustrate why they got you.

I remember that I would get very annoyed if someone  had their hands low but kept dancing in and out of range to prevent me from capitalizing.
Inexperienced kickboxers that adopted this strategy (often because they had a point karate or taekwondo background) I would maneuver until their back hit the dojo wall.
The experienced ones would see what I was doing and maneuver around me, covering their movement with their jab.
It's not right: if you do things the Right way you will be good at fighting - but you're doing things the Wrong way and I still can't touch you.
In reality, once you get a good enough feel for timing and distance you can afford to drop your hands here and there.


I developed pretty impressive punching and kicking power while training kickboxing (it turns out, pads, bags, and people make much more realistic targets than the air - who knew?), but actually landing anything was a different matter.
It was as if I was simply too slow, every time I attacked I'd get countered, if I tried to counter they'd slip right through the hole in my defense.
I could be completely ready, and their attack would slip through my guard before I'd even registered they're moving.
A beginner's wild haymakers I could reliably block, but with little time to spare to counter.
Not every time, some days I'd be able to keep up a little - I still have a little highlight reel in my head of moments that worked out well.
Still, more often than not I was a punching bag.

This wasn't helped by the advice I'd read online: that the quickest way to improve is to find the best, toughest guy in the dojo and spar with them.
So I mostly picked parners that were taller and more experienced.
And then I was patient.
Just keep training and you will improve, obviously.

One day I felt dizzy after training.
I had been very passive in sparring, I think one of my training partners tried to helpfully shock me out of that passivity.
It backfired though: even though I willed myself to go on the offensive my body wouldn't obey me.
I steeled myself before each round and managed a few slow, hesitant attacks which were promptly countered.
Then I spent the rest of each round hiding behind my gloves.
I realized then, reflecting, that this had been happening more and more over the last months.
After almost two years of training I wasn't getting better - I was getting worse.
Now on top of that I was dizzy from blows to the head - I was risking the health of my brain for this sport.

Could my inability to improve be attributed to dyspraxia?
Yes and no: dyspraxia should surely make me learn slower, and eventually lead to a lower skill cap.
I wouldn't expect it to be this big a difference though: after two years I was worse than most first-timers.
There were definitely a few other factors: the gym was very full and the instructor had very little time for helping individuals.
The sparring culture was fairly competitive, people always tried to maintain the upper hand and would up the intensity to keep it.
I'll explain later why I believe that this approach to sparring is detrimental to the less talented members of the school, and what the alternatives are.
Thirdly, the instruction was concerned with the techniques - doing them well and chaining them together smoothly, but I don't recall learning much about distance and positioning.
Most schools seem to expect people to pick up on these aspects intuitively during sparring; and that expectation is usually, but apparently not always, correct.
Most important however was my own psychological approach to training and where it led: into a state of [[id:277b1451-9929-43bf-a225-9a2570b7aadf][learned helplessness]].
It would be years before I knew what that was or how it could explain my inaction during sparring.
I simply concluded I was very slow to react and innately unsuited to kickboxing.

non-combat sports never hold my interest for long.
I need to stay in shape somehow, and martial arts are the only steady athletic interest I have.
Dropping martial arts altogether never crossed my mind - I decided I just wasn't suited to striking.
I've got a slow build, and slow reflexes besides.
Now the groundfighting part of the MMA classes I'd been trying here and there seemed to play to my strengths better.
being on the ground everything is a little slower anyway.
It's all about technique and knowledge - so even I can get good at that.
Learning the basics of groundfighting was reinvigorating.
Unlike with striking, there truly is a near insurmountable advantage to doing things the right way.
I was convinced I could continue to improve until I was good at it.

