:PROPERTIES:
:ID:       a1a77873-0e53-4cd4-ab21-b4782d86d240
:END:
#+title: the-noonday-demon

There is only one chapter summarized here because after that I became too engrossed to stop and make a summary regularly.
I will probably reread it, and at this point you may get more summaries from me.

* Depression

Solomon takes a stab a defining Depression. This chapter uses a lot of poetic language, because Solomon says that depression is best understood through metaphors.
The chapter is somwhat meandering, and so it is hard to recall each point and topic, so I may need to revisit the chapter to get all of them.
He emphasizes that while depression is chemical, just like every mental experience, this has a complex interaction with our experiences.
He emphasizes that just as we address the ozone depletion even though we have sunscreen, we should address the social elements contributing to depression.
He concludes the chapter by mentioning how depression forms a part of the emotional spectrum, andd should be dealth with, but not elimanted.


