:PROPERTIES:
:ID:       02504069-e1e7-43c8-a746-43ed27a2f807
:END:
#+title: serotonin-and-heplessness


* The link between serotonin and helplessness

Sometimes something bad is happening and there is nothing you can do about it.
Sometimes it only feels that way.

A child studies hard for a subject she finds challenging but despite her best efforts still gets a low grade.
She is told off for this, and though she tries to sit down and study again she finds that she can't concentrate.
She's lost the will to study and lost the feeling that doing so will lead to a better grade.
Now that she is struggling to concentrate, she's not entirely wrong.
Helplessness is a powerful inhibitor of learning.

The researchers Martin Seligman and Steven Maier explored the psychology behind this phenomenon.
They performed a series of experiments on various mammals where they had three groups.

 - Escape group, they were exposed to something unpleasant and had a way to escape it (e.g. pulling a lever)
 - Non-Escape group, they were exposed to something unpleasant without any way to escape it
 - Control group, they were placed in the experimental setup but didn't have to do anything

After this all three groups were placed into a new environment where there was an unpleasant stimulus.
They could escape it by a different means than the escape group learned (e.g. jumping over a barrier).
The Control and Escape groups learned how escape just fine.
The Non-escape group however generally did not, and had to be physically moved to safety repeatedly before they started to take action themselves.

Maier and Seligman recently wrote an engaging and thorough retrospective: [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4920136/][learned helplessness at fifty]]. They discuss the psychology and neuroscience of this phenomenon.
For me, reading about these distressing experiments reminds me of days where I was depressed, and knew on some rational level that going out - for instance to a cafe - would help, but in my gut feeling that no matter what I do nothing will ever make me feel better.
If I had been living alone, I probably wouldn't have done much besides feel sorry for myself.
I had to be pushed out the door time and time again before my instinct would allow me to take that step myself.

Animals exposed to these conditions of helplessness display many symptoms of depression.
Learned helplessness has become one of the major theories of depression, and probably describes at least part of the picture for many patients.
It's an especially interesting theory for me because it links depression to anxiety, and describes a prominent role for serotonin.

For the following sections I'll be summarizing the overall picture the evidence presented by Maier and Seligman paints, but rememeber that it is one interperetation of this evidence, and not the only valid one.
If you want an explanation of the experiments so you can evaluate the evidence itself, Maier and Seligman's paper does that better than I can.

** The role of the DRN in helplessness

Remember the dorsal raphe nucleus (DRN)?
Unpleasant stimuli activate the DRN and the amygdala. The amygdala is best known for its role in fear, so it's not surprising it would be activated in these circumstances.
The DRN neurons affect (among others) the amygdala and striatum.
The striatum is mostly known for playing a role in deciding whether or not to act.
When the DRN releases serotonin in the amygdala it makes the animal more fearful.
When the DRN releases serotonin in the striatum, it makes the animal more passive.
Serotonin is also released within the DRN itself, where it activates 5HT1A receptors which reduce the firing of the neurons.
The DRN is therefore self-inhibiting: the more it is activated, the more it inhibits itself.

If an animal believes it is able to control the stimulus, cells in the ventromedial prefrontal cortex activate and silence the DRN.
This frees up the animal to act.
If the stimulus is inescapable however, these neurons do not activate and the animal remains passive.

When the DRN fires and activates its own 5HT1A receptors, these receptors slowly desensitize, becoming less sensitive to serotonin.
This makes the DRN more active and harder to silence when it is next activated.
Maier and Seligman suggest that this is what causes learned helplessness.


There is some indication of a more complicated picture: [[https://www.nature.com/articles/nature11617][one study]] found that when they activated the DRN overall they saw increased activity from an animal instead of passivity.
This conflicts with some of the studies mentioned by Maier and Seligman, and may be related to the different activation methods they used activating different subsets of the DRN.
Additionally, my understanding of the 5HT receptors in the DRN is that they desensitize for a few hours, while learned helplessness can persist for much longer.
It seems to me that their theory is incomplete.
So as usual in biology, it likely isn't as simple as it at first appears.

Additionally, it's important to note that the neuroscience side of learned helplessness hasn't been studied much in humans yet, and could be different for us.
Although many studies on the psychology of learned helplessness and its relationship to depression have been done in humans, the experiments on the neuroscience of it have mostly been done in rats and mice.
More work is necessary to see if this applies to humans too.

You may notice that under this theory a depressed state is one in which __more__ serotonin is released rather than __less__.
So why do drugs that increase serotonin levels tend to alleviate depression?
We don't know. It's possible that their action is somehow related to this mechanism.
On the other hand, remember that serotonin comes from raphe nucl/ei/, as in plural, as in there is more than one of them.
The dorsal raphe nucleus is just one of these nuclei, and the amygdala and periaqueductal grey just two of its many targets.
Other raphe nuclei, or even other neurons in DRN which have axons targeting other regions, may have very different effects.
# TODO: bring up karl diesseroth's studies and the habenula here.
# there's a lot of work still to be done on this topic.

I picked this description of the role of serotonin because it is the clearest picture I could find, and it gives a workable theory for the relationship between anxiety and depression.
It is just a very, very small part of the picture, even if it looks like a crucial part.
This story is at odds with the theory that most people have heard: that depression is the result from not having enough serotonin in the brain.
Let's tackle that topic next.

* key takeaways

- when animals are powerless to stop something unpleasant, they act depressed
- this includes being passive, and behaving powerless even when they are not
- the release of serotonin by the DRN is associated with this helplessness behavior
- If the animal realizes it has control, the DRN will be silenced by neurons in the prefrontal cortex.

next: [[id:9c8961f2-4dbd-4dc9-9cd5-f498abc8afaa][the-serotonin-deficiency-theory]]


