:PROPERTIES:
:ID:       9c8961f2-4dbd-4dc9-9cd5-f498abc8afaa
:END:
#+title: the-serotonin-deficiency-theory


One of the most well-known theories of depression is the serotonin deficiency theory.
The theory is that depression is a result of having too little serotonin in the brain and can only be corrected by increasing the amount of serotonin, for instance through drugs.
The main evidence [[https://doi.org/10.1192/bjp.113.504.1237][presented for this theory]] at first was the fact that drugs which increase the release of serotonin help to alleviate depression.
Initially these were [[https://en.wikipedia.org/wiki/Monoamine_oxidase_inhibitor][drugs which affected a number of neurotransmitters]] besides serotonin, but the theory led to the development of more specialized drugs with more specific effects.
[[https://en.wikipedia.org/wiki/Selective_serotonin_reuptake_inhibitor][selective serotonin reuptake inhibitors]] (SSRIs) block the activity of a protein called SERT.
SERT takes serotonin in the brain and absorbs it - to clean it up and metabolize it.
So if SERT is blocked then any serotonin released is going to float around for longer and is more likely to interact with 5HT receptors.
Hence, reuptake inhibitors.

The attention the serotonin deficiency theory got was not unwarranted - the truest trial of a scientific idea is not merely a match with the evidence, but whether it can be used to develop beneficial technology.
For a while, this theory passed that test.

Pharmaceutical companies selling SSRIs naturally latched on to the theory and used it extensively in their marketing, which is why it is so well known among laypeople.
However, in spite of extesive efforts new evidence for the serotonin deficiency theory has been hard to find, and as a result it never formed a firm scientific consensus.
Most research into depression has regarded serotonin deficiency as (at best) one factor of many in the pathlology of depression.
Recently, a splash was made by a [[https://www.nature.com/articles/s41380-022-01661-0.pdf][paper]] by Joanna Moncrieff and colleagues which shows that attempts to demonstrate a relationship between serotonin concentration and depression severity have not borne fruit.
They excluded studies using animals and studies focusing on specific subtypes of depression, and tried to answer six questions:

 1. whether people with depression have lower concentrations of serotonin in their bodily fluids
 2. whether the levels of 5HT1a receptors are lower in people with depression
 3. Whether people with depression have more SERT or more active versions of SERT
 4. whether depleting serotonin can cause depression
 5. whether the gene for SERT is more expressed in people with depression
 6. whether a mutation of the SERT gene combined with stressful events leads to depression


For each point they were unable to uncover compelling evidence.
When I was reading papers for this blog entry, I did find papers which were cited as evidence for many of the 6 claims analyzed by Montcrieff. et al.
I'm going to assume that if I ran into these papers while looking into it casually, they encountered them as well when conducting a professional review and excluded them for good reason.
# TODO: email montcrieff and ask.
# TODO: look into a few other articles


So why do SSRI's still work? Montcrieff suggests that they have the effect of dulling emotions in general, helping patients deal with depression more easily.
However, there are loads of other things SSRIs do and therefore many, many theories about how they help with depression. I'll get into a few others in later posts.

** takeaways

 - medications like SSRIs help patients recover from depression
 - however, there is next to no evidence of the theory that depression is the result of a serotonin deficiency
 - there are many possible explanations for why SSRIs work, with no clear leader


