:PROPERTIES:
:ID:       00813f54-3bba-432c-8032-acc000dc5311
:END:
#+title: serotonin-and-learning
 
# TODO: I wonder if by not going into as much depth, I maybe make it less engaging. If I don't give the audience a firm, intuitive grasp of the topics being discussed I feel like I might not draw them in.

Serotonin plays a role in the process of learning.
Exactly what role is not clear, but it seems to be especially involved with un-learning and re-learning.
Learning happens in the brain by changing the strength of connections between neurons (and other stuff too, but connections are a major one).
This is called synaptic plasticity.

* Synaptic plasticity

The way neurons are connected to one another isn't set in stone.
Recall that the locations where neurons signal to one another are called synapses.
The strength of the effects of these synapses can change over time, and sometimes synapses disappear or new synapses grow.

These changes are thought to be how animals learn:
 - lived experiences cause the neurons to fire in particular patterns
 - the synapses change in response to these patterns (and potentially in response to other things too)

   
** Hebbian plasticity

The most common form of plasticity in the brain is called [[id:14baaec1-d68e-4fab-88a0-8e51986e4499]['Hebbian]]', after Donald Hebb who hypothesized it in 1949.
When one neuron releases the neurotransmitter glutamate onto another neuron, most of the time this has the effect of bringing that neuron closer to releasing a neurotransmitter itself.
You can see it as one neuron telling another to speak up.

When this works - one neuron releases glutamate to another, and then that neuron releases its neurotransmitter, the connection between them tends to strengthen.
Otherwise, it tends to weaken.
This is often remembered as 'cells that fire together wire together', and conversely: 'fire out of sync, lose your link'.
So the strength of the connection is affected by the presynaptic activity and the postsynaptic activity.

Hebbian plasticity can explain a great deal about how stimuli (sights, sounds, etc.) are efficiently encoded by the brain.
It can also enable the efficient storage and retrieval of memories, and build associations between things.

** Third factors

We know from efforts to apply hebbian plasticity to AI that it only gets you so far.
Not all stimuli are equally important to encode, not all associations are important, and not everything should be a memory.
Those hebbian plasticity rules based on the activity of the two cells can be affected by other factors.
One way the brain does this is through the release of different neurotransmitters, such as dopamine, ephinephrine, and our good friend serotonin.

We are only just beginning to explore the immense complexity of these effects: in fact, for serotonin I was only able to find one study, on one type of cell expressing a specific serotonin receptor regarding how it changes plasticity at this level.

Ordinarily, when you make one cell spike (release neurotransmitter), and then make a cell it is connected to spike, the connection between them strengthns.
[[https://www.cell.com/neuron/fulltext/S0896-6273(15)00826-0][The paper]] showed that when the cells they studied were sprayed with serotonin afterwards, this effect was reversed.
This actually matches quite nicely with some behavioral experiments I've read about.

* 

   

* Serotonin in plasticity 
Various studies show effects of altering serotoninergic activity on the process of plasticity.

A common method for assessing the plasticity of a mammal's cortex is to cover one eye and assess how the responses in its visual cortex change in response to this.
The visual cortex is a region of the brain which processes what is seen by the eyes - so if you cover one eye you change the kind of input this region is recieving.
The covered eye is signaling nothing - so in time the visual cortex should learn to take its cues only from the uncovered eye.
In young animals this happens quite readily, but in adults it takes much longer.

This method has been used to look at how serotonin affects plasticity.
It turns out that when you deprive young animals of serotonin, their visual cortex does not learn to only respond to the open eye (Gu and Singer 1995, Bradley et al. 1987).
Conversely, when you increase the amount of serotonin in the cortex by adiministering an SSRI, adult visual cortex learns more similarly to a young one (Vetencourt et al. 2011).

Since plasticity is learning, another important way of studying it is of course by observing the capacity of a test subject to learn a task.
Hence, a second kind of experiment on plasticity is called [[id:a13dcc9a-91d5-46a1-aa2b-4c960626f1f7][reversal learning.]]
In a reversal learning experiment subjects are first taught to do things one way, and once they get the hang of it they have to learn to do the exact opposite.
It is seen as a way to measure cognitive flexibility.
One way to try and relate these learning tasks to the underlying biology is to genetically or pharmacologically alter animals and see how it affects their performance.

Recall from  [[id:9c8961f2-4dbd-4dc9-9cd5-f498abc8afaa][the-serotonin-deficiency-theory]] that the serotonin transporter SERT is responsible for moving serotinin back into the cell that emitted it.
Reducing the activity of SERT will make it so that serotonin released from your neurons lingers for longer and will be more likely to affect nearby neurons.
[[https://academic.oup.com/cercor/article/20/8/1955/40590977][Brigman et al. 2010]] Found that when you either genetically or chemically reduced the activity of SERT in mice, they more quickly learn to reverse their task.

A third way that plasticity is studied involves attaching glass pipettes to neurons in a slice of brain tissue for manipulating and recording their electrical potential.
A basic approach is to attach a pipette to one neuron, attach a pipette to another, then stimulate the first cell to see if it causes a change in the potential of the second.
If so, the first cell is connected to the second and that connection can be studied.
You can record the strength of the effect the first cell has on the second, then stimulate both cells to make them fire in particular patterns, and then record the strength of the connection again.
[[https://www.cmor-faculty.rice.edu/~caam415/lec_gab/g4/markram_etal98.pdf][In the 90s, Henry Markram used this method extensively]] to study hebbian plasticity in cells.
Making the first cell spike and the second soon after generally strengthens the connection.
Making the second cell spike and the first soon after generally weakens the conection.
This is called Spike-timing dependent plasticity and is a fairly straightforward way for hebbian learning to be implemented.
One experiment suggests that serotonin may turn this on its head.

[[https://www.cell.com/neuron/fulltext/S0896-6273(15)00826-0][A paper from 2015]] (which I found via [[https://pubmed.ncbi.nlm.nih.gov/30108488/][this excellent review ]]) found  that if you make the postsynaptic cell spike right after the presynaptic but spray a little serotonin on it the connection actually gets weaker instead of stronger.
It's just one paper studying one interaction in one brain region in one species of animal so almost any broader statement on the basis of it is highly speculative.
It is consistent however with a possibility I have been thinking about for a while.

* Learning and unlearning depression

These are a few choice examples from the [[id:aab01968-25fd-4714-8016-682095ad0f43][growing list]] of studies I've found indicating that serotonin specifically plays a role in un-learning.
It enhances plasticity by allowing the subject to change existing patterns.
It has been [[https://www.sciencedirect.com/science/article/pii/S0306453010002301?casa_token=zMNJ58V1W_AAAAAA:JW9cxCqnS68UxW_iE5ArLB8xd3DwfBQO5rCX6JokorIt7cfIkDYxzdU414Qbf0_k9lJSipTuXg][suggested]] that this effect of serotonin is responsible for the antidepressant effects of SSRIs, but also that it may be important for the development of depression in the first place.
By enhancing the ability to change the way you think, SSRIs can help you break out of unhealthy cognitive habits.
We also have some evidence that serotonin plays a role in getting depressed in the first place.

Considering what we know about [[id:02504069-e1e7-43c8-a746-43ed27a2f807][serotonin-and-heplessness]], the un-learning capabilities of serotonin could well play a role in animals un-learning the ability to respond to a situation, and thereby make way for helplessness.
If you take some action, but it turns out to be no use, then serotonin is released and weakens the connections that led to that action.
I personally consider this a more compelling explanation for learned helplessness than the sensitization of the DRN [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4920136/][suggested]] by Maier and Seligman.

* key takeaways

 - When you learn, the the connections between neurons change - those that activate at the same time get stronger connections, the rest weaker
 - Serotonin appears to affect this specifically by reversing it - allowing you to un-learn and hereby re-learn more easily
 - This could explain the role it plays in both the development and recovery from depression

# When an animal is put in a helpless position and their DRN starts releasing serotonin into their cortex it would make the cells that are firing in concert weaken their connections, and thereby suppress whatever thoughts or behaviors the animal is having going forward.
# Un-learning the ability to think of a way out of the situation may be a direct effect of serotonin stimulation.
# # Remember that serotonin receptors come in different types.
# # When He et al. suppressed the 5HT2c receptor they found that putting serotonin on the cell no longer weakens the connection of the spiking cells.
# # Interestingly, the wikipedia article on 5HT2C receptors contains a variety of claims linking increases in their activity in depression and anxiety, and decreases in their activity with recovery.
# # for the claim that the therapeutic effects of SSRIs come at the same time as decreases in 5HT3c receptor downregulation, the link was to an article which did not discuss this - I think this was most likely an accident.
# # For the claim that 5HT3c receptors are more active in suicide victims, a paper https://www.nature.com/articles/1395631 is cited which found
# # 1. no significant differences in RNA editing (not sure what that means) between depression, schizophrenia, control populations
# # 2. significant difference in suicide victims
# # I'm not convinced that the RNA editing they're talking about means increased efficacy in suicide victims
# # Although the effect size was very large and the result significant, the sample size was still small
# # I'd say this needs a replication or two
# # for the claims regarding effects of some antidepressants on 5HT2C efficiency, I found some decent sources.
# # However, I'm not sure if this is meaningful in itself - I'm sure a huge variety of drugs have some effect on loads of receptors
# # what is the prior probability that a random drug, effective or not for depression, has an affinity with some receptor, and is it really much lower than the posterior if they are effective.
# It is interesting that this receptor is involved, since it has specifically been researched for its role in [[id:277b1451-9929-43bf-a225-9a2570b7aadf][learned helplessness]].
# [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3415988/][One study]] finds that increasing the activity of 5HT2C receptors increases the expression of learned helplessness after social defeat (in hamsters).



# This does seem to match what I suggested before; that serotonin plays a role in un-learning.

# As I look into it, I find a [[id:aab01968-25fd-4714-8016-682095ad0f43][growing list]] of studies indicating that changes related to serotonin specifically affect learning from failure.
# Not all of them are consistent with the idea that the release of serotonin leads to un-learning.

# https://www.cell.com/neuron/pdf/S0896-6273(13)00789-7.pdf [[id:b04fba1a-e7ee-4320-ab00-2099bf50ee97][denOuden-dissociable-2013]]
# https://www.jneurosci.org/content/25/2/532.short [[id:656608d6-3e8a-4b8a-bf50-972fb7a221f7][clarke-prefrontal-2005]]
# https://www.nature.com/articles/npp2009233
# https://www.nature.com/articles/s41380-021-01240-9
# https://www.sciencedirect.com/science/article/pii/S030645221600244X?casa_token=HQQ7sNlVtREAAAAA:RhX4ALapUtgx54gmpsTxHwoLoZgwGb02neRpAlOnXW4E0kG_-R5tk_zyeYYtiAfjjo2Wd3uNNg


# * mice, serotonin, learning

# _martinowich_interaction_2008
# schmidt_identification_2012

# * What does serotonin signal in learning?

https://www.researchgate.net/profile/Povilas-Karvelis/publication/359631505_A_Computational_Model_of_Hopelessness_and_Active-Escape_Bias_in_Suicidality/links/6247046d7931cc7ccf0bb4fa/A-Computational-Model-of-Hopelessness-and-Active-Escape-Bias-in-Suicidality.pdf?_sg%5B0%5D=started_experiment_milestone&origin=journalDetail&_rtd=e30%3D

