:PROPERTIES:
:ID:       fdf0b971-5273-4565-9a24-b4b85be36a6e
:END:
#+title: serotonin-and-resilience
This is a stub for a topic I plan to write about, starting from this article:

The Deakin/Graeff hypothesis proposes that while the dorsal raphe nucleus potentiates fear and anxiety, the medial raphe nucleus instead provides resilience.
see: [[id:1d3f59ef-0400-46c0-bafb-b67c0fa0e463][paul-deakin-2014]]
[[id:52e8b7d2-e2af-4029-8325-7cb5dcc401d9][johnston-failure-2015]]
[[id:be5432d2-eb14-40a7-9650-9eac3a900fd6][fgraeff-role-1996]]
[[id:664af7d8-098b-4106-ae65-a58dcf4db40d][paul-functional-2013]]
[[id:f71e5eae-e3b3-46e1-bc3b-36acae8fd803][pereira-both-2019]]
[[id:167fae2c-3d7a-4999-8466-9839da0ef11a][krystal-noradrenergic-2009]]
[[id:1e6d5090-70c2-4173-868a-98111931d59d][prakash-serotoninergic-2019]]
[[id:9e16748b-995c-457f-b6cd-6077af3e39aa][lesch-serotonin-2011]]
[[id:ed91a96d-07bf-4d39-8ff4-35d8c33a8795][deakin-5-ht-1991]]
[[id:a69897af-aa62-4623-8e41-1b3810e14c54][kawai-median-2022]]
[[id:a996c379-6371-4981-8fc1-e74e8e9c263a][murrough-serotonin-2011]]
[[id:f99cce24-3a87-4d40-9127-8b89d39a6d9e][hyun-investigation-2018]]
[[id:4389efe3-728e-4bc7-84aa-3d2cefe63d64][carli-role-2020]]
[[id:93fa48e5-4376-4325-a80f-88ce67e765fa][wipfli-serotonin-2008]]
[[id:8923feb8-462f-47fb-b41a-654be26fe80e][wipfli-examination-2011]]
[[id:d3865a7e-db2d-4709-9135-347d4e8edeba][oglodek-changes-2022]] 
[[id:7ce46dc5-6808-47ad-aba5-9bb922c994fd][strong-role-2012]]

PTSD 





paul-vincent strong's work, perhaps more relevant to learning or helplessness?
(The Role of Central 5-HT2C Receptors in Stress-Induced Anxiety and the Anxiolytic Effects of Exercise


https://www.ibroneuroscience.org/article/S0306-4522(11)01126-2/abstract



! idea : ecs-based large-scale simulations, simulate for a long time, identify markov blankets and emulate blanketed mechanisms to accelerate future simulation.

https://www.nature.com/articles/d41586-025-00675-2


IMPORTANT:
https://www.nature.com/articles/d41586-025-00383-x


https://www.sciencedirect.com/science/article/pii/S0166432817304527
https://www.sciencedirect.com/science/article/pii/S2213231723004068

https://www.cell.com/neuron/fulltext/S0896-6273(14)00955-6


https://link.springer.com/chapter/10.1007/978-1-4614-4048-2_4


Serotonin as an acceptance molecule.
There is nothing you can do, don't try.
There is nothing you can do, don't worry.
These have to go together.
You change direction and focus your effort and mind elsewhere,

Resilience is not the same as persistence.
Adaptability and acceptance may well be its essence.
