:PROPERTIES:
:ID:       00813f54-3bba-432c-8032-acc000dc5311
:END:
#+title: serotonin-and-learning
 
# TODO: I wonder if by not going into as much depth, I maybe make it less engaging. If I don't give the audience a firm, intuitive grasp of the topics being discussed I feel like I might not draw them in.

Serotonin plays a role in the process of learning.
Learning happens in the brain by changing the strength of connections between neurons (and other stuff too, but connections are a major one).
This is called synaptic plasticity.

* Synaptic plasticity

The way neurons are connected to one another isn't set in stone.
Recall that the locations where neurons signal to one another are called synapses.
The strength of the effects of these synapses can change over time, and sometimes synapses disappear or new synapses grow.

These changes are thought to be how animals learn:
 - lived experiences cause the neurons to fire in particular patterns
 - the synapses change in response to these patterns (and potentially in response to other things too)

   
** Hebbian plasticity

The most common form of plasticity in the brain is called [[id:14baaec1-d68e-4fab-88a0-8e51986e4499]['Hebbian]]', after Donald Hebb who hypothesized it in 1949.
When one neuron releases the neurotransmitter glutamate onto another neuron, most of the time this has the effect of bringing that neuron closer to releasing a neurotransmitter itself.
You can see it as one neuron telling another to speak up.

When this works - one neuron releases glutamate to another, and then that neuron releases its neurotransmitter, the connection between them tends to strengthen.
Otherwise, it tends to weaken.
This is often remembered as 'cells that fire together wire together', and conversely: 'fire out of sync, lose your link'.
So the strength of the connection is affected by the pre(before)-synaptic  activity and the post(after)-synaptic activity.

Hebbian plasticity can explain a great deal, from efficient encoding of visual scenes to memory.
For example, think of the way a smell can transport you to a familiar memory.
Those neurons that were coding for that smell and the neurons coding for other sensory inputs were all active together.
So they connected together, and when a few of them are active they now activate the rest and transport you back to that moment.


** Third factors

We know from efforts to apply hebbian plasticity to AI that it only gets you so far.
Not all stimuli are equally important to encode, not all associations matter, and not everything that happens should be a memory.
So synaptic plasticity based on the activity of the two cells can be affected by other factors, such as pleasure, fear, curiosity, or pain.
One way the brain broadcasts feelings like pain and fear is through the release of different neurotransmitters, such as dopamine, norepinephrine, and our good friend serotonin.

We are only just beginning to explore the immense complexity of these effects.
While I'll get into various caveats towards the end of the post, most work finds that serotonin is especially important for the ability to un-learn things you had learned before.

* Serotonin as an error signal for learning.

The most prominent hypothesis for how serotonin influences learning is that it works in [[https://www.nature.com/articles/npp2010151][opposition to dopamine]].
While dopamine has been viewed as encoding appetite, motivation and action, serotonin has been associated with satiety, passivity, and inaction.

This opponency theory can partly explain how [[id:aab01968-25fd-4714-8016-682095ad0f43][increasing serotoninergic signaling improves the ability of an animal to un-learn something it learned previously]].

Remember how, due to hebbian plasticity, when two neurons fire together the connection between them is strengthened.
If this activity pattern leads to a good outcome you would want this effect to be especially strong - which dopamine, among others, is proposed to do.
If this activity pattern leads to a bad outcome however, perhaps you do not want to strengthen it: perhaps you want to do the opposite.

This is precisely what Dr. [[id:d1b21711-da73-457c-a686-902f86fb3f36][He and colleagues]] observed serotonin does in the visual cortex.
If you apply the same rule in simulations it [[https://www.cell.com/cell-reports/fulltext/S2211-1247(22)00397-7][reproduces the effects of SSRIs on the ability to reverse learning]].


Although the idea of serotonin as a passivity signal dovetails nicely with what we have learned so far about [[id:94ac0879-77e6-4b0a-be68-7b0c9de848a6][learned-helplessness]], recent work suggests a more nuanced role for serotonin in learning.
[[id:9f3f755b-5764-41ea-a709-44e2f51e1ad4][Serotonin sometimes reinforces the effects of dopamine rather than opposing them]]
Rather than simply signaling bad outcomes, serotonin-emitting neurons in a region called DRN respond [[id:9801d89b-3de0-4d60-b2f8-b0d9b26957d0][both when things go worse than expected, and when things go better than expected]].
This emerging perspective places serotonin as a key molecule for signaling surprise and uncertainty.
Besides explaining how serotonin influences the ability to un-learn (if things aren't as you expect, forget what you think you know), as well as anxiety and hesitancy (in which uncertainty is an important factor).


** Learning and unlearning depression


Recall from [[id:9c8961f2-4dbd-4dc9-9cd5-f498abc8afaa][the-serotonin-deficiency-theory]] that SSRIs, the most common antidepressants, increase the action of serotonin in the brain by ensuring it floats around for longer without being reabsorbed.
SSRIs sometimes take several weeks to reach their full effect in a depressed patient, which was one challenge to [[id:9c8961f2-4dbd-4dc9-9cd5-f498abc8afaa][the-serotonin-deficiency-theory]].
Understanding serotonin as a driver of learning may explain this delay.

[[id:aab01968-25fd-4714-8016-682095ad0f43][Various experiments]] demonstrate that increasing the effects of serotonin through SSRIs makes animals better at changing established patterns of behavior, while decreasing it has the opposite effect.
Learning is a gradual process, so it is possible that the gradual effects of SSRIs have to do with learning, rather than with some immediate chemical effect.
An important part of cognitive behavioral therapy is breaking self-destructive patterns of thought and behavior.
It may be that SSRIs work at least in part by making it easier to break these bad mind-habits.

However, recall from [[id:02504069-e1e7-43c8-a746-43ed27a2f807][serotonin-and-heplessness]] that the release of serotonin by the neurons in the dorsal raphe nucleus is related to the creation of depression-like states.
In a state of learned helplessness, in which an animal will be unable to evade an easily escapable threat due to prior experiences of helplessness, is prominently mediated by serotonin.
A signal that reverses plasticity in active neurons could also play a role un-learning the ability to act in response to a threat.
[[https://www.sciencedirect.com/science/article/pii/S0306453010002301?casa_token=zMNJ58V1W_AAAAAA:JW9cxCqnS68UxW_iE5ArLB8xd3DwfBQO5rCX6JokorIt7cfIkDYxzdU414Qbf0_k9lJSipTuXg][It has been suggested]] that the plasticity-ehancement by serotonin therefore plays a dual role in depression - both in its pathenogenesis and its recovery.


* holes in the story

Something about this doesn't add up however.
If the action of serotonin both generates and alleviates depression, it would be expected that taking SSRIs would leave a healthy or largely recovered individual more vulnerable to developing depression.
I was always reccomended to maintain my dosage, /especially/ during high-risk periods.
Indeed, I've found research suggesting SSRIs promote resilience, and been unable to find any suggesting they undermine it.
Again, I would like to emphasize that SSRIs do work, we just don't understand why.
When it comes to matters of medicine, listen to your doctor rather than the still-germinating speculations of theoretical neuroscientists.

As I've hinted already, not all studies are consistent with the idea of serotonin as an un-learning chemical.

 - Above we discussed how the experiment by Dr. He and colleagues showed that a specific receptor (5HT2C) is a natural candidate for explaining the un-learning effects of serotonin.
   However, [[id:e545e2db-f6de-4375-931b-3dc909793c03][two]] [[id:9ee2e52d-ff0e-4a67-b8b8-bdfb7da96607][experiments]] found that reducing its activity actually increased reversal learning, which is the opposite of what you would expect given this!
   Additionally, some SSRIs cause a [[https://karger.com/nps/article-abstract/63/3/160/233469/Antidepressant-Treatments-Change-5-HT2C-Receptor?redirectedFrom=fulltext][decrease in the density]] of these receptors in the long term, suggesting they are not important for un-learning depression.
 - The results regarding the effects of specific receptors are highly inconsistent, and probably depend on a number of factors (compare [[id:e545e2db-f6de-4375-931b-3dc909793c03][boulougouris-dissociable-2008]] and [[id:27d09b0a-307d-441d-898b-ccae3903f2d6][frick-dual-2015]], for example)



Perhaps the next chapter in serotonin's story can help make sense of this.
Besides being implicated in helplessness, depression, and learning, serotonin is also implicated in psychological resilience.
Rather than the Dorsal Raphe Nucleus, which we have mostly discussed so far, this seems to involve more of its neighbor, the Medial Raphe Nucleus.
I'm looking forward to looking into that.
Stay tuned.


* key takeaways

 - When you learn, the the connections between neurons change - those that activate at the same time get stronger connections, the rest weaker
 - Serotonin appears to affect this specifically by reversing it - allowing you to un-learn and hereby re-learn more easily
 - This could explain the role it plays in both the development and recovery from depression
 - However, there are several pieces of evidence that do not line up with this, suggesting a more complex picture

# When an animal is put in a helpless position and their DRN starts releasing serotonin into their cortex it would make the cells that are firing in concert weaken their connections, and thereby suppress whatever thoughts or behaviors the animal is having going forward.
# Un-learning the ability to think of a way out of the situation may be a direct effect of serotonin stimulation.
# # Remember that serotonin receptors come in different types.
# # When He et al. suppressed the 5HT2c receptor they found that putting serotonin on the cell no longer weakens the connection of the spiking cells.
# # Interestingly, the wikipedia article on 5HT2C receptors contains a variety of claims linking increases in their activity in depression and anxiety, and decreases in their activity with recovery.
# # for the claim that the therapeutic effects of SSRIs come at the same time as decreases in 5HT3c receptor downregulation, the link was to an article which did not discuss this - I think this was most likely an accident.
# # For the claim that 5HT3c receptors are more active in suicide victims, a paper https://www.nature.com/articles/1395631 is cited which found
# # 1. no significant differences in RNA editing (not sure what that means) between depression, schizophrenia, control populations
# # 2. significant difference in suicide victims
# # I'm not convinced that the RNA editing they're talking about means increased efficacy in suicide victims
# # Although the effect size was very large and the result significant, the sample size was still small
# # I'd say this needs a replication or two
# # for the claims regarding effects of some antidepressants on 5HT2C efficiency, I found some decent sources.
# # However, I'm not sure if this is meaningful in itself - I'm sure a huge variety of drugs have some effect on loads of receptors
# # what is the prior probability that a random drug, effective or not for depression, has an affinity with some receptor, and is it really much lower than the posterior if they are effective.
# It is interesting that this receptor is involved, since it has specifically been researched for its role in [[id:277b1451-9929-43bf-a225-9a2570b7aadf][learned helplessness]].
# [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3415988/][One study]] finds that increasing the activity of 5HT2C receptors increases the expression of learned helplessness after social defeat (in hamsters).



# This does seem to match what I suggested before; that serotonin plays a role in un-learning.

# As I look into it, I find a [[id:aab01968-25fd-4714-8016-682095ad0f43][growing list]] of studies indicating that changes related to serotonin specifically affect learning from failure.
# Not all of them are consistent with the idea that the release of serotonin leads to un-learning.

# https://www.cell.com/neuron/pdf/S0896-6273(13)00789-7.pdf [[id:b04fba1a-e7ee-4320-ab00-2099bf50ee97][denOuden-dissociable-2013]]
# https://www.jneurosci.org/content/25/2/532.short [[id:656608d6-3e8a-4b8a-bf50-972fb7a221f7][clarke-prefrontal-2005]]
# https://www.nature.com/articles/npp2009233
# https://www.nature.com/articles/s41380-021-01240-9
# https://www.sciencedirect.com/science/article/pii/S030645221600244X?casa_token=HQQ7sNlVtREAAAAA:RhX4ALapUtgx54gmpsTxHwoLoZgwGb02neRpAlOnXW4E0kG_-R5tk_zyeYYtiAfjjo2Wd3uNNg


# * mice, serotonin, learning

# _martinowich_interaction_2008
# schmidt_identification_2012

# * What does serotonin signal in learning?

# https://www.researchgate.net/profile/Povilas-Karvelis/publication/359631505_A_Computational_Model_of_Hopelessness_and_Active-Escape_Bias_in_Suicidality/links/6247046d7931cc7ccf0bb4fa/A-Computational-Model-of-Hopelessness-and-Active-Escape-Bias-in-Suicidality.pdf?_sg%5B0%5D=started_experiment_milestone&origin=journalDetail&_rtd=e30%3D


# https://www.sciencedirect.com/science/article/pii/S0166432814003994
# https://www.sciencedirect.com/science/article/pii/0091305779901667
# https://www.jneurosci.org/content/27/3/684.short
# https://link.springer.com/article/10.1007/s00213-017-4684-8

# https://www.biorxiv.org/content/10.1101/2024.05.06.592810v1.abstract
# https://www.sciencedirect.com/science/article/pii/S0969996118300871
# https://www.sciencedirect.com/science/article/pii/S1053811921009745


# I need to re-write most of this, start with a new structure and copy paste bits again.
