:PROPERTIES:
:ID:       0bda671e-a72d-4f39-a5f5-c670e7d8345c
:END:
#+title: devlog-20240808

Ok, I've come up with a few more things that need to go in the MVP

1. make the dash distance consistent
2. ensure dash and enemy attack dash/distance are well matched for the appropriate counters

But I won't get around to that today, instead I have to un-fuck the animations.

See, I wanted to have a system underlying the mechanics of the movement representing the angle of the vector from their left foot to their right.
The character is be easier to offbalance at 90 degrees to this vector than parallel to it.
Their left and right feet take turns stepping to align with their position, while the non-stepping foot is sationary.
The idea was that this would add some extra depth to the gameplay.
However, with the other elements for players to work with and grasp, it so easily fades into the background anyway.
More importantly, getting the movement animations to align well with this has been a nightmare and I've had very little success.
It is not important to get this in the MVP, maybe in the finished product, even that I think unlikely.

So I fucked up the animations and stuff by adding this unnecessary element.
Parts of the functionality are embedded in the sprites, the movement, the posture, and of course the rendering.
I can get the old animations pretty easily I think, but finding and removing the dead code and wasted cycles will be tricky.

Bah, It didn't quite go back to how it was. I'll need to fiddle with it some more.
There is a lot to tweak, from sprinting speeds to animation strides.




My mind wandered, some old ideas I had forgotten about floated up.
 - Shockwaves when an enemy hits the ground can briefly offbalance struck enemies, similar to the strike-based stun
 
