:PROPERTIES:
:ID:       94473826-b302-43e7-9fcf-3d2691c45911
:END:
#+title: Violence, proportionality, and self defense

In a gym in Amsterdam, an instructor grimly tells us how to deal with someone who places their hand on your shoulder from behind.
You pinch their fingers between your ear and shoulder and violently turn to face them, breaking their fingers.
Then, of course, you batter their groin with knees.
And the first timers are left wondering: in what situation is that actually the appropriate response?

Of course, we practiced it very slowly and without any kind of resistance or reaction from the "assailant".
But there was a lot of tough talk, a very serious atmosphere.
It felt raw, real, even though the violence was practically symbolic.

This way of approaching self defense is neither unique to Krav Maga nor universal to it.
It is pervasive enough in a variety of martial arts communities to be [[https://youtu.be/3CGMWlXosp4?si=u89Bwgyx5KcWmPmZ&t=115][be the subject of parody]].

Krav Maga is marketed as being used extensively by militaries and police forces.
American police are often sent to train alongside israeli police.
Several organizations have noted a similar, and similarly agressive, approach to policing in both countries.
And perhaps there is no better indictment of the paranoia of Krav Maga's philosophy than the failure of this method of policing in the USA.

Among these failings of self defense and policing there is a lesson about conflict resolution, martial arts, human relationships, and analogous lessons in international relations.

* The failings of brutality

Krav Maga is not actually a specific martial art.
It refers to any hand-to-hand fighting taugh to the israeli military.
In terms of technique, that could be anything from aikido to boxing.
What sets it apart is the emphasis on building aggression over technique, doing damage over maintaining control.
No draftee heading off to war has time to master martial arts, you just need to make sure they fight hard.

The branded krav maga taught to civilians does tend to have some technical cohesion, mediated by the organizations that sell it.
There are specific techniques and principles, but the most consistent one seems to be this: do stuff you aren't allowed to do in combat sports.
Hit the groin (a lot), gouge eyes, snap fingers.
Technique doesn't matter: what matters is that you're meaner than the other guy.

In online communities dedicated to combat sports Krav Maga has been the target of ridicule ever since it rose to widespread popularity.
In Mixed Martial Arts, the examples I have seen of Krav Maga fighters involved the Krav fighter being handily controlled by the combat athlete.
They never even recieved an opening where they could have used a groin kick or eye poke had they been allowed.
If you want to gouge someone's eyes, you need to get past their defenses to touch their face.
If you want to kick someone's groin, you need to manage the distance and set it up just like any other kick.
So you need a certain parity of skill if you're going to use these techniques.
And conversely, if you have a sufficient skill advantage, you don't need to use them.


* The violent power of compassion

What is the alternative?
What does build that kind of skill?
The exact opposite: focus on techniques that are safe to apply and apply them for real.
When Judo (at the time, Kano-ryu Jujitsu) was emerging as a martial art this was the philosophy that set it apart from other Jujitsu styles.
Nowadays in competitions like mixed martial arts, where it is permitted to violently wrench an opponet's joints, those who prevail are not those who spend time practicing this, like in pre-judo jujitsu.
Those with the greatest success are those who focus on techniques with a lower risk for injury - especially wrestling and brazilian jiu jitsu, but also other combat sports like boxing, muay thai and indeed Judo.


The advantage to an individual fighter isn't just that they get injured less, but that their training partners get injured less.
In BJJ circles it is a saying that the more you help your training partners improve, the more they will have to teach you.
Martial arts training has an inherently cooperative element, which helps prepare people for the eventual competitive aspects.
Which brings me to another point about how a less aggressive approach to preparing for violence is actually more effective.

I do not want to overemphasize the importance of training intensity and realism - facing off against a partner who is fighting hard to best you is a crucial part of training, but the growing consensus is that this should not be most of your training.
Any martial arts forum will furnish you with complaints of people going 'too hard' in sparring practice or focusing on "winning" over learning.
Most of your sparring should be at substantially less than full speed and less than full force, as this lowers the risk of injury.
Futhermore, it is important to adjust to the level of your partner and not resist them so hard that they are completely shut down.
To keep both parties learning and challenged, both parties need to have opportunities to work, to attack, defend, and counter.
I once recieved advice to seek out the tallest, most skilled person in the school to spar with for kickboxing - as they're the greatest challenge and therefore the best learning experience.
It turns out that being so outclassed that everything you do ends in failure is not actually conducive to learning.
On the contrary, it is so bad for learning that it is used as an experimental protocol for inducing a [[id:02504069-e1e7-43c8-a746-43ed27a2f807][helpless state in which learning ability is impaired]].

So the central theme is not so much resistance and intensity (although that is important), but freedom of play and safety from injury.
Where the high-brow pacifistic musings of some (especially buddhism-influenced) martial arts and the actual development of combative skill meet is here: to develop a group of students into capable fighters they must learn to exercise kindness towards one another.

"As long as we coexist, each member of society and the groups organised
within must function in harmony and cooperation with the others.
Nothing is more important than living prosperously together. If everyone
acts with the spirit of mutual cooperation, each person’s work benefits
not only himself, but also others, and attaining this together will bring
mutual happiness. [...] This great principle of harmony and
cooperation is, in other words, the concept of Jita-Kyoei, or mutual
prosperity for self and others."
 - Jigoro Kano, founder of Judo, in an essay published in 1925, this translation is from *The Gentle Way, Maximising Efficacy and Minimizing Violence in Judo* by Dario Mazzola


* The cowardice of cruelty

I don't wish to imply that people don't have a right to seriously harm others when they defend themselves.
All that is necessary to secure your safety is justified.
Harming the other party only becomes an issue when it is unnecessary or counterproductive.
Of course it will be hard to recognize in the moment where justified self defense ends and retribution begins.
I have no doubt that the retributive impulse is in fact very important when it comes to avoiding victimization.
Accordingly, the law is rightly lenient with those who overstep when responding to a threat.

The reality and magnitude of that threat is important.
If you are attacked by an unarmed person of a weak and diminuitive stature, say a child, you have no right to seriously injure them no matter how murderous their intent, and no matter how much you dislike them.
The responsibility to avoid harm rests with the party with the upper hand.
The party with control over the situation is the party with the luxury and obligation of deescalation.

"Self defense" focused combatives like civilian Krav Maga often market themselves as protecting you from a dangerous world.
Although rates of violent crime have been decreasing across the developed world, people nonetheless feel threatened by the possibility of violent crime.
Using hypothetical assaults by bands of armed strangers, "self defense" systems promise you security from violence.
Besides safety, they offer retribution: "we do bad things to bad people" says the marketing catchphrase of Deutsche Krav Maga Verband in 2022.

Germany today - like most european countries - is a very safe place to be, safer than it has ever been and unfathomably safer than most times and places throughout human history.
In the unlikely event that you are attacked it will not be by a group of strangers but almost certainly by an acquiantance.
The retributive, aggressive attitude of KM and similar schools is an expression of an irrational fear.
Capitulation to an irrational fear to the detriment of yourself and others is cowardice.


A reasonable response to this may be: "Wouldn't you rather be prepared in the event that such an attitude is justified?"
Isn't such an eventuality worth preparing for?
In the case of combat in the ring aggression and a focus on maiming techniques may not get you far - but self defense situations are different from an arranged fight.
Discounting for the moment the psycholgical and social costs of hyper-vigilance, I admit the concession that being psychologically prepared to hurt another person can help to protect you in a violent confrontation.
In self defense, unlike in the ring, you don't need to out-fight your aggressor, only to make them believe it is more trouble to mess with you than it is worth.
This brings us to a much broader point.
Contrary to the way it is discussed by most practitioners of martial arts (thus far, myself included), hand-to-hand combat is the least important part of self defense.
Women's self defense specifically has been a topic of a small but significant amount of empirical research.
The findings of this research are flattering neither to combat sports nor Krav Maga.

* Evidence-based self defense

TODO: place more emphasis on the fact that bad SD focuses incorrectly on assaults from strangers
TODO: perhaps mention the symmetry that once again, that skill in non/minimally violent means removes the necessity of more violent means
TODO: waffly - what exactly do I want the readers to get out of this. Focus on that, if they want the full picture they can follow the links.

When I went looking for [[id:5d38c8d0-8c5e-4dee-8f04-5427a806c285][peer-reviewed articles on self defense]] I found that all the evidence based literature was focused on women's self defense.
Although [[https://www.sciencedirect.com/science/article/pii/S1359178907000766?casa_token=3DvBAIeZ9IAAAAAA:tErJw-u3458JUwdfI7TstyKi1o3AmYhoBR5tDdwDyZvW7VWZViuVd56kVmz04SPYhC3S9zhQVw][some evidence]] exists for benefits from a variety of self defense courses, only one approach (as far as I could find) has solid, systematic, controlled data collection backing it up.
This is [[https://compass.onlinelibrary.wiley.com/doi/abs/10.1111/soc4.12597?casa_token=a_u-H1-xxVYAAAAA:ep0_5otMwbp3xzbalKCcxyKrLAipUO7e6GXbxdsSSW6q73XMV97u7Jc28FiTUHEY6NK4ds76lq4BUQ][Empowerment self defense]] (ESD), researched extensively by Jocelyn Hollander.

A very interesting aspect of this research, at least reading as a martial artist, is that the physical techniques are the least important aspect of the training.
Rather, much of the education in ESD focuses on the setting, communicating, and enforcing of boundaries, and of understanding one's rights.
This isn't to say that the physical side of self defense doesn't matter.
Women who fight back physically when assaulted are more likely to get away safely, and have better psychological outcomes even if they fail to.
Women who recieved a physical self defense course are more likely to fight back, and more likely to do so successfully.

Jumping straightaway to the nuclear, groin-destroying, eye-blinding option is not a feature of these self defense systems.
Rather, they offer a range of techniques for interrupting an assault before it comes to that.
So, why not jump to the nuclear option? If a stranger ambushes you and attempts to rape you, don't you have every right, and every reason to jump straight to this?
-- TODO: I need to track down the sources I found before for this
The fact of the matter is that stranger rape is the exception, not the rule when it comes to violence against women.
The vast majority of sexual assaults are perpetrated by acquaintances, family, friends, and especially intimate partners.
The use of extreme violence in these situations brings with it social and psychological consequences.

This is also why the non-physical strategies and traits imparted by ESD are so important.
The research shows that when ESD is taught to populations of women they are not just better at protecting themselves - but less likely to be assaulted in the first place.
We need to understand that sexual violence, indeed all violence, is socially situated and involves aspects of manipulation, coercion, rationalization and justification.
Resistance to these non-physical means of enacting violence in personal relationships plays an important role.

The ambitions of many martial arts, for example Judo, extend beyond providing physical skills, safety, and physical education to its participants, but also to exert a transformative influence on society.
This is an ambition that ESD shares, and Hollander emphasizes its potential in changing the culture that creates violence against women.
How our fighting arts understand and respond to violence shapes the culture in which violence takes place: so we had best ensure that, like ESD, our conceptions of violence are based in reality.


* Our flawed understanding of violence

file:///home/hugs/Downloads/49-Artikeltext-279-3-10-20190123.pdf
https://psycnet.apa.org/record/2010-13682-006

I would argue that the naive, inaccurate understanding of violence that pervades martial arts communities is convenient, contaigious and pleasurable for us because it justifies our fantasies of violence.

* community policing, prison abolition


* A missile is a machine that creates terrorists


* 
