:PROPERTIES:
:ID:       e545e2db-f6de-4375-931b-3dc909793c03
:END:
#+title: boulougouris-dissociable-2008

5HT2A an 5hT2C are two types of serotonin receptors which seem to have different effects when activated.

Boulougouris et al. treated one set of rats with a drug that reduces the activation of 5HT2A and another set with a drug that reduces the activation of 5HT2C receptors.
They had the rats perform a [[id:a13dcc9a-91d5-46a1-aa2b-4c960626f1f7][reversal-learning]] task and compared them to a control group.

Neither affected the ability to learn or retain the task, but reducing 5HT2A activation reduced reversal learning performance while reducing 5HT2C activation increased reversal learning performance.
I find that this contrasts sharply with [[https://www.cell.com/neuron/fulltext/S0896-6273(15)00826-0][this paper]] , where they found that in the cortex 5HT2C receptors were specifically involved in inducing LTD in temporally coupled cells.
This seems like exactly the kind of functionality you'd need to speed up reversal learning, but deactivating this receptor actually makes it faster?
On the other hand, this does seem more consistent with the idea that stronger 2C activation leads to a more stubborn learned helplessness.



