:PROPERTIES:
:ID:       2a6e3f2c-622b-4654-9a53-98a1fc2a8c80
:END:
#+title: metaphysics-of-programming

When we write programs there are different ways that we can organize our code.
Different ways of programming, especially in computational science, constitute different ways of representing the sructure of the world.
Questions regarding the structure of reality fall under the domain of metaphysics.
Metaphysical assumptions are embedded in computer programs, and often have parallels in historical metaphysical theories.

Metaphysics is by its nature not demonstrable - we do not have access to reality as it really is, so we will never truly know what it consists of.
Despite this, we all reason about a real world and make assumptions about it in order to navigate our surroundings.
We must assume a metaphysics, even if we cannot demonstrate that our metaphysics is true.
The role of metaphysics then is organizing thought, not establishing truth.
It is about analyzing our mental representations of reality and how these constrain and empower us.
In my view then, discussing programming practices can lend itself to metaphysical questions, and metaphysics can help us with programming questions.

* Object Oriented Plato

TODO: there is a disconnect at the heart of this - what is real? stateless processes that determine the transitions of state (functions, classes), or only those things that represent state?

The dominant programming methodology for the last forty years or so has been Object Oriented Programming (OOP).
In classical OOP a program - including the parts of it that represent a real-world system- consists of objects which are instances of classes.
A class represents a category of object, like a Chair class represents the category of chairs, while your living room chair is a specific instance of that class.
Any specific chair has additional, changeable properties like color, position, or velocity (during particularly heated arguments).
The class of chairs itself though does not (strictly speaking) have these properties and is defined one way, and stays that way.

Those familair with classical greek philosophy have likely already spotted a parallel.
In Plato's metaphysics the objects we interact with in the real world are instances of some eternal, perfect "form" that defines them.
The form in this case is similar to a class, and the real object is an instance.

This approach to programming and metaphysics has limitations.
For one thing, the world loves to defy classification (a detailed argument can be found [[https://karl-voit.at/2017/04/18/classification/][here]].)
Things in the natural world tend to blend together and be clustered together only loosely.
The desire to categorize and organize the world to understand it is common, understandable, but I think often misguided.
Besides this, it is sometimes difficult to say where one object ends and the other begins.
We often (and rightly) end up separating objects based on practical concerns rather than what clearly and concisely describes the model system.

A lot of the more advanced object oriented principles and design patterns concern working around these limitations.


* Entity-component systems as property-cluster realism

In [[id:e1bf5827-0366-4bd5-8542-a77de9096a9c][extending-ourselves]] Paul Humphreys argues a metaphysics for computational science called property-cluster realism.
In property-cluster realism it is not objects that are real, but the properties we associate with those objects.
If you percieve a hot iron bar, it is not the iron bar that is real, but the heat, the ferromagnetism, the shape.
The ways in which the rest of the world is affected are the things that are meaningfully real in this metaphysics.
The 'object' is just the clustering together of properties in space and time.

This resembles an entity-component system architecture.
ECS is most often applied in games, where the objects in the game world are the 'entities', and things like position, velocity, health, team are components.
The entity in an ECS is nothing more than an identifier used to group properties together.
While there are Enity-Component architectures where game logic is implemented on the components, in a pure ECS game logic is offloaded to systems.
Systems contain no state - that is for the components, they only describe the rules by which state evolves.

Entities and components are intended to enable categorical flexibility: instead of needing to define distinct classes and using inheritance to reuse code, you can define new categories of entities by simply attaching a different combinaion of properties.
It is an extreme application of the common maxim "prefer composition to inheritance".
The offloading of logic to systems is partly for flexibility; by not binding logic to components you can change the rules governing their interactions by enabling or disabling systems, and you can more easily organise logic that spans multiple components.
However, the main selling point is related to efficiency.
Due to the way CPU caches work it is more efficient to store components of the same kind together and operate on arrays of components (vectorizaion) than it is to go object-by-object.
ECS is a form of Data-Oriented Design.

ECS is not explicitly used much in computational science.
Smaller studies often don't have much of an architecture to begin with.
Simulation engines often use object-oriented interfaces and do any vectorization under the hood (NEURON for instance).
NEST has something similar to an entity-component system, although it does have rigid classifications for entities (Nodes, Connections) and clear separation of logic between them.

I think that ECS can allow for simulation code that is both performant and expressive, and it does so because of its practical metaphysics.
The variables written into the simulation directly represent proposed properties, observable by their interactions with the world.
Segregation of the laws governing their dynamics from their data representation allows for clear descriptions of natural law.

I'm an oddball who finds that code is often a clearer expression of an idea than prose, but that is only true when the clarity of the code, and its correspondence to the real world, are a priority.
OOP often involves the introduction of abstractions which are of pragmatic, implementational significance.
With an ECS I find it easier to keep these out of the part of the code involved in represetning the system of interest.

- note: ECS and OOP are not mutually exclusive, as OOP is often used to define ECS architectures (see: Concord).

* BDD - beyond metaphysics

https://karl-voit.at/2017/04/18/classification/
