:PROPERTIES:
:ID:       e53c1c8e-0500-4e10-8a87-321cd926b74e
:END:
#+title: devlog-20250403


Today I'm playing around a little with the Enno fight.

I noticed when you stick close to Enno, it gets a little awkward with his attacks.
They're easy to dodge, and he flies away from you making chasing after him a bit of a chore.
So I'm thinking of brining back an old mechanic: Enno will push you away.

An interesting point here is that I'm going to try it out, and it may or may not remain.
If I write tests, they may be wasted.


But it is not a trivial mechanic.
In this case, I had implemented it before.
But if I needed to implement it from scratch, automated tests might be helpful anyway.
And in this event, I wouldn't have to re-design and rewrite it after prototyping.

If the change were trivial, I could implement it first, then write tests if I decide to keep it.

In this case, I am not writing tests, we shall see if that was a good idea.



I'm keeping it, it gives the fight a very hectic feel.

I noticed a few other issues though: I changed the knockback from punching to offbalance the target, this makes it too easy to punch people into a barrel.
Secondly, there was a bug on level 7, the enemies could not navigate to the player.
