:PROPERTIES:
:ID:       83472889-eda0-4354-a1d4-9615916efd1d
:END:
#+title: Why does the lunge punch exist?

* The widespread lunge punch
If you've done karate, taekwondo, or most styles of kung fu for any length of time, you have seen something like this:

[[yt:CQdYtXsOYLs?start=9]]

The practitioner steps forward into a lunge and punches with the same hand as the stepping leg.
This is a basic technique, part of the bread and butter of styles like shotokan.
It features less centrally in many other styles, and many traditional grappling-focused arts feature defenses against it in their curricula as well.

However, you will not see this movement at all in combat sports, because it is almost always a bad idea in a full-contact fight.
Isn't it odd that such a bad technique is so widespread?
How did that happen? There are many possibilities.
Maybe the technique has been misinterpereted?
Maybe it makes more sense in the contexts in which these arts were originally developed?
Or maybe it truly doesn't make sense, but became widespread anyway?
These kinds of dumb questions interest me, maybe they will interest you too.

* why are there no lunge punches in combat sports.

Let's start with why it's a bad idea.
In full-contact striking sports you generally move towards your partner by taking small steps forward with your lead foot.

[[yt:kKDHdsVN0b8?start=141]]

These small steps are quicker and harder to exploit than a fully committed walking step.
You do see walking steps in boxing and kickboxing, but they generally are taken diagonally, moving off your partner's line of attack and moving around them when they are already in range: a repositioning, not a gap-closer.
If you step straight towards an opponent with a big comitted step not only do they have plenty of time to see your attack coming, but you may well run straight into their fist and knock /yourself/ out.
If you're at a range where you can't reach with a small step, you don't try to charge in from a distance, you first get a little closer, and then engage properly.

Even in point karate competitions, where force of strikes doesn't matter, this footwork does not show up.
Techniques labeled as 'oi-tsuki' (japanese name for the lunge punch) do show up and consistently score (see  [[https://aassjournal.com/article-1-760-en.html][this paper]]),  but they do not use the traditional footwork.
If you step through to chase an opponent, you do not punch with the lead hand but with the rear, and use the pushing motion to propel your step forward.

(like [[yt:6zOR34e8LDU?start=273&end=275]])


If even in karate competitions this technique doesn't work, why is it so widespread?

* The need for speed

One explanation, from Christopher Hein, is that when one person automatically wins by creating enough disance, closing that distance becomes imperative for the other.
[[yt:aA5KerxdwCQ?start=212&end=229]]

In aikido, defenses against lunge punches show up in a lot of practice.
Hein provides a possible explanation for this.
For arts predating aikido, a samurai engaged in hand-to-hand fighting wants to create distance to draw their sword.
For aikido itself, someone defending themselves from attack wants to create distance to get away.
The attacker in this context has to close the distance by any means necessary. explaining the presence of so many lunging, charging, and grabbing attacks that you learn to defend against in jujutsu-derived arts.
A step-through lunge punch covers more distance with the strike than the competitive distance closers you see in competitions.

This may explain defenses against lunge punches, but could it also explain the lunge punches themselves?
For karate, maybe.
Karate forms, at least those in shotokan, are full of big gap-closers.
There is some reason to believe that traditional karate was, unlike modern competitive karate, a heavily clinch-focused style built around grabbing someone before you hit them.
The kicks present in the shotokan kata I learned are all gap closers followed by some sort of grabbing and pulling motion.
The lunge punch, also called the 'chasing punch' may be a way of 'sticking' to a retreating attacker once you have grabbed them.
In shotokan, I was taught to extend my non-punching hand at the start of the movement, and pull it back on executing the punch.
That makes much more sense if you're grabbing someone before you hit them.
This also explains why you are taught to pull one hand back to your waist when you strike: you are using that hand to pull your opponent off balance.
Ian abernathy, a specialist in practical applications of traditional karate movements, suggested something similar [[https://iainabernethy.com/content/step-through-punch][in a forum post]], although the video links he provides are broken so I cannot verify how closely his idea resembles my own.


What about other styles in which they are present?
In taekwondo and korean karate it is explainable by the influence from japanese karate.
Many kung fu styles show a lot of the things that I attribute to clinching in karate and so may have a similar focus, but frankly I am not well qualified to comment.
I shall have to let others take the lead there.

* Could lunge punches be based on armed fighting?

What if, instead, it is a hold-over, a transfer from armed fighting?
In longsword fencing from HEMA it is common for beginners to learn and to practice against attacks that in many respects resemble a lunge punch.

[[yt:dvu-XUu2ytY]]

The timing of initiation of the strike is different though - the strike begins at the start of the movement, going in front of the swordsman and protecting them as they close the distance.
A similar movement seems to be present in kenjutsu as well.
However, when we look at competitive venues for weapons fighting - kali, kendo, HEMA competitions, this footowork is once again exceedingly rare.

[[yt:U0IyAG-a1is]]
[[yt:uWa8KSnfZNg]]

The fact that the mystery of the lunge punch is echoed in armed fighting presents a problem for the explanation that the lunge punch is a holdover from armed fighting.
Since this is true also for symmetric sword arts focused on dueling, like italian longsword, it poses a challenge to our previous explanantion that lunging comes from an asymmetric need to close the distance.
This explanation cannot explain the presence of a step-through lunge in longsword "basics", since it is for a symmetric context.


* Is the lunge punch a teaching tool?

A different explanation for why these techniques are studied is offered by Dan Djurevic.
He describes a concept he calls [[https://www.wayofleastresistance.net/2013/01/kata-techniques-as-stem-cell-movements.html]["stem-cell" movements]].
By this he means techniques that you do not actually use, but that teach good habits and patterns of movement that come in handy when learning the practical techniques.
He [[https://www.wayofleastresistance.net/2012/10/kata-kinaesthesia-and-proprioception.html][likens this]] to playing scales on stringed instruments to build basic proprioception and motor habits.
The kata, through techniques like the lunge punch, teaches principles of movement that will apply to the practical techniques you learn later on.

There is an important difference between playing scales and lunge punching.
When you play scales you play the notes and move between them the same way you will play them in a song.
This is untrue in a lunge punch.
Sure, any complex exercise will improve your proprioception, stability and coordination.
But the idea here is that doing the wrong movements over and over, ingraining the wrong movement patterns, helps you to learn the right ones in the end.
Dan explains this claim thoroughly, but does not substantiate it.
In my opinion, a claim like this needs to be justified before it is believed.

I find this explanation convoluted and without evidence.
It seems to me an attempt to rationalize a way of training, rather than evaluate it.
The only reason to believe it rests on an assumption.
It is the same assumption that prompts this post, the heart of the contradiction of the lunge punch.
People, including many solid fighters, have trained this way for over a hundred years, that means there must be a good reason for it.
But must there really?


* Maybe it just sucks?

This leads us to a final final possibility: maybe it just doesn't matter that it sucks.
Technique is subordinate to skill - timing, balance, intuition. TODO link icymike
A movement that works your muscles well, feels good to do, and looks powerful may well become widespread despite teaching bad technique.
I feel this may explain a lot of differences between what we see in older martial arts and what works best in full-contact fighting.

This ties into a recent debate in Judo.
The way you are first taught techniques, and indeed the way you mostly practice technqiues as a novice hobbyist, differs markedly from the way they are executed in competitions.
Novice and intermediate judoka have been complaining about this for decades, and mostly been dismissed.
Since the release of a video by (todo mention credentials) Cho Junho and Cho Junhyun, it is finally being taken seriously by more experienced practitioners.

[[yt:_M9GTgz41lQ?start=14]]

Talented, experienced athletes can easily rationalize training the traditional way - they practice that way and they're very good at what they do.
"It teaches fundamental principles you need for the practical variations", they say.
"It is an exaggerated movement that becomes smaller and tighter in application."
But this simply isn't true.
The basic variations teach inefficent biomechanics, their principles and habits often directly the opposite of the habits you need to execute the technique for real.

As the Cho brothers pointed out, experienced competitiors only do a little bit of traditional training as a warm-up, and spend the bulk of their training sparring and working competitive techniques.
Novices and hobbyists in contrast are severly handicapped by this approach because they remain stuck training "basics" while not getting any better at actually throwing people.
As someone who trained BJJ and MMA before Judo the contrast is incredibly clear.
In the former three you practice techniques the way you use them, and you also get to a basic level of competence fairly quickly.
Judo's reputation for a harsh learning curve is well earned, and it may mostly be due to this one issue.

The reasons given for training basics the wrong way first in judo always reminded me of the rationalizations had heard for karate techniques.
Many of them resemble the explanation Dan provided for the lunge punch.
Judo provides an example of bad training persisting in a community of otherwise competent martial artists.
Perhaps the lunge punch is nothing more than this also.
