:PROPERTIES:
:ID:       99261cbb-2ad0-4962-9bbe-3337d92f094f
:END:
#+title: Grieving the white knight


A few months ago, I played the game Hitman: Absolution.
It's a stealth game from 2012.
Something very 2012 stood out to me, resonated with me, and made me cringe.
The game's narrative centers around protecting women from a slew of misogynistic villians.
In other words, it's a bit white knighty, and oh god do I hate how much I loved that.
The "white knight" fantasy has, from what I can tell, just about vanished from western gaming.
I think there are good reasons for that, but I miss it nonetheless.
I wonder then, should the white knight make a comeback, better than before?


* The game


Hitman: Absolution is a stealth assassination game.
You play agent 47, a tough, scary-looking dude with a garotte and a bunch of guns, and your objective is to assassinate a target while limiting other casualties.
The plot centers on a young girl, Victoria, who has been genetically engineered to be the perfect assassin.
47 seeks to help Victoria escape the organization who created her - his employer - and spare her the life he lived.
It doesn't take long for her to be kidnapped from his care, and the bulk of the game is a string of missions in pursuit of her, leaving a minimum 20 corpses in your wake.
(If you're bad at the game, or just impatient, you leave several hundred corpses.)

* The villains


The villians you are protecting Victoria from are portrayed as misogynists, consistently victimizing women, and you positioned as the protector of Victoria from them.
As an one example, one of your first targets is the abusive owner of a strip club, who exploits, assaults, and sometimes kills his employees.
It isn't only women that the villians harm, but it is mostly women.
The only female characters on the villain's side are the bad guys' secretaries, largely belittled, ignored, and sexually harassed by their bosses.


* The women

Fortunately the game doesn't sexualize Victoria.
This is a paternal protectiveness, very popular in other games at the time (the last of us, bioshock infinite).
Her entire existance and character is constructed to feed the player's desire to protect her: she is helpless, dependent, young.

What, you thought the genetically engineered super-assassin would be some sort of badass?
Nope, not without a necklace which is conveniently far from her he whole game - except in one [[https://www.youtube.com/watch?v=LPKViQ7vTr4start=410][hilarioulsy inconsequential scene]] at the end.
Oops, we left [[https://en.wikipedia.org/wiki/Chekhov%27s_gun][Chekhov's gun]] lying around! Quick, shoot it in the air before the story ends!

The agency of women in the game is limited not just by the men around them, but also by the design of the game: it naturally centers on the player's experience.
Their inner lives and struggles are sometimes portrayed, but their actions seldom affect the plot.
This kind of blind, unintentional misogyny is common for the era of gaming: the player is assumed male, assumed straight, and their experience is naturally the important thing to focus on.
Men besides the player are given power: they are the antagonists after all, and the power they wield to get in the player's way is how the gameplay happens.
Women however are either eye candy, inanimates to be saved, or both.

This game was criticized by a prominent feminist game critic for portraying women as objects for the player to sexualize and abuse.
This criticism was only half right.
The women in the game are objects of abuse, but for the villains, not the player.
During the period surrounding the publication of this game, women who discussed games online with a feminist lens were subjected to targeted harassment campaigns, a backlash in part to feminist criticisms of common gaming tropes.
This coordinated backlash is remembered as "Gamergate".

There are other topics the game engages with through its villains: police brutality, corruption, greed, hostility to "bleeding heart" journalists.
The way these are framed and portrayed, and the way the narrative opposes them left me with an impression of a generally progressive ethos.
This is unsurprising, artists and young people generally skew progressive: game developers are artists, and gamers were generally young.


* The death of the white knight


Playing the game, I found progressive ideas embedded in its plot and worldbuilding, though it is more accurate to say regressive ideas are embedded in its villains.
Before Gamergate happened, I felt that this was the case for gaming culture in general.
So what happened, in my view, when the inadvertent sexism in the medium was pointed out, is that a lot of young men were utterly blindsided.
"What, I'm not sexist! These games are clearly anti-sexist! I'm the Good Guy. It's the Bad Guys that are sexist. All this effort saving the princess and this is the thanks I get?"
Of course, not in those words.

My characterization of this reaction, based on my own experience in this demographic, is intended to illustrate two facts about the white knight fantasy.

1. It is cringe.
2. The reason it is cringe is that it is disingenuous

In internet lingo more broadly, the "white knight", or "nice guy" stereotype often refers to a man who pretends to respect or stand up for women to get attention.
If he isn't sufficiently appreciated for it, he gets upset and in the process reveals he didn't really respect women in the first place.
Likewise, the white knight fantasy portrayed in such games isn't really about women's auotnomy - it is about the virtue of the man defending it.

You could argue that this is partly the case for anything moral.
We do moral things not simply because they are moral, but also because it brings us satisfaction to /be/ moral.
But there are different kinds of satisfaction to be had: a self centered kind and an other-centered kind.
The satisfaction may come from percieving yourself as virtuous, or from expecting some future reward - which is self-centered.
But the satisfaction can also come from empathy, from the pleasure of seeing the positive effect you have had.
This is an other-centered kind of power trip.

* Resurrecting the white knight

I've had discussions with young men online who state that they feel unwelcome in progressive movements because there is no role for them to fill except that of the villain.
Yes, for others to be heard traditionally powerful groups like men do need to shut up and listen, but it's not much of a sales pitch is it?
Come to the light side, we have guilt and lectures.

A white knight story provides a satisfying role for a man to play in the fight against sexism.
And the problem with male-centered power fantasies was never their existence, but their ubiquity.
For a long time if a game was anything else it was lucky to get made at all, let alone have a good budget and marketing.
It may reflect a change in my taste rather than the games themselves, but I feel like this particular style of power fantasy has vanished entirely from western gaming.
That wasn't necessary.

As power fantasies go, the fantasy of being a good man who selflessly helps the powerless is pretty damn benign.
Pernicious elements can very easily make their way into it, but I think when it is thoughtfully employed, in a self aware, other-centered way, it is valuable and compelling.
Instead of emphasizing the victimization the white knight protects people from, emphasize what the protected become and achieve once empowered.
The white knight, after using his power to protect the vulnerable, should ultimately surrender some of it to them.
This ensures tha the fun of the fantasy is focused on the effect on others, rather than the self.

In the fantasy of being a protector of women, misogyny is a necessary component.
With the resurgence of misogyny and hostility to feminism in online spaces there will be plenty to go around.
We need an emotionally resonant role for men in fighting it, we need the white knight.

Rise, Sir Cringealot: a new quest beckons.
Reconquer the darkened land of nerddom.
Protect the princess.
But you have to mean it this time.

# [[yt:LPKViQ7vTr4?start=4156&end=4212]]
