:PROPERTIES:
:ID:       72d2a1a8-da5d-49cf-856a-c6b3abe6ed71
:END:
#+title: a-little-neuro-game

I develop computational models of nervous systems as a profession, and I develop games as a hobby.
I've often thought about bringing these two together, but I struggle to come up with neural concepts that make for engaging gameplay.
Well, I've made a little prototype, and personally I felt engaged, though so far playtesters have struggled to figure out what to do.

In Forging Foraging there is a little organism who needs to collect food. It can see, and it can move, but it needs your help.
Your role is to construct its nervous system: connecting and creating neurons to let it collect food efficiently enough to not starve.
As it grows, so will its food needs and consequently you need to improve its search strategy to keep up.
Click the link above to download and play it, and let me know your experience with it!


In a way computational modeling is a natural fit for certain styles of video games.
You use models to create a simulated world and let the player play in it.

However, what makes a good computational model is not necessarily what makes an engaging player experience.
In particular, when we decide to computationally model a system, it is usually because it is very hard to understand.
A good game is clear in its rules : the player should know how their actions will affect the world so they can plan and play accordingly.
A computational model is hard to make work as a game world, unless it simplifies out the subtle interactions that you actually really want it to capture.
It's not impossible to make good gameplay out of subtlety, I just don't know how yet.

While Forging Foraging can show basic concepts like synapses, spiking, excitation, inhibition and sensorimotor loops, it is missing the most important feature of neural systems: their capacity to learn.
Real behavior emerges from neurons changing their connections and traits based on experience.
It would be cool to get a player to figure out how to implement this with tools they are given.

This would require a much richer, more complex world for the organism, in which it needs to learn and recognize patterns, plan and adapt.
There are many ways I could do that, all of them effortful.
Another challenge is communicating such complex mechanics as synaptic plasticity to a player without making them watch a theoretical neuroscience lecture.
Even with an understanding of the neuroscience, the process of putting it together could easily become overwhelming, and therefore not fun.

Well, maybe I'll have more ideas someday.
