:PROPERTIES:
:ID:       99261cbb-2ad0-4962-9bbe-3337d92f094f
:END:
#+title: lamenting-the-white-knight

A few months ago, I played the game Hitman: Absolution.
It's a stealth game from 2012.
Something stood out to me, something very 2012 resonated with me and made me cringe.
It's a bit white knighty, and oh god do I hate how much I loved that.


As the name suggests, Hitman: Absolution is a stealth assassination game.
You're a tough, scary-looking dude with a garotte and a bunch of guns, and your objective is to assassinate a target with as little collateral as possible.
The plot centers on a young girl who has been genetically engineered to be the perfect assassin.
Following your coworker's last wish you seek to help her escape the organization - your employer - who created her and spare her the life you lived.
It doesn't take long for her to be kidnapped from your care, and the bulk of the game is a string of missions in pursuit of her, leaving a minimum of one corpse per mission in your trail.
(If you're bad at the game, or just impatient, you leave several hundred corpses.)

The game positions you as (among other things), a gentleman protecting women from a slew of misogynistic villains.
It provides a power fantasy blatantly pandering to young men, and meanwhile provides very little agency to the women in its story.
But progressive politics permeate it and the game clearly doesn't want to be misogynistic in doing this.

Fortunately, it doesn't sexualize the girl being protected.
No, this is much more a paternal protectiveness, very popular in many games at the time (the last of us, bioshock infinite).
If you thought that the genetically engineered super-assassin would be some sort of badass in the story, you would be surprised.
She is entirely helpless without a certain necklace - which her captors wisely keep far from her person.
She therefore spends almost all the game as a limp, half-sleeping mcguffin.

Oh she does cut loose once, in a hilariously pointless scene towards the very end of the game.
For no disclosed reason she is suddenly wearing her necklace, and when grabbed from behind goes full john wick and kills a buncha guys.
Then she is grabbed from behind exactly the same way, and captured again like nothing happened.
Oops, we left Chekov's gun lying around! Quick, shoot it before the story ends!

Other female characters show up, on the arm of a bad guy 
