:PROPERTIES:
:ID:       29be628d-4e89-411c-ac4c-e378f1b18904
:END:
#+title: acceptance-versus-helplessness


I've [[id:02504069-e1e7-43c8-a746-43ed27a2f807][written before]] about helplessness in depression.
When animals are exposed to unpleasant stimuli with no control or escape, they display depressed behaviors afterward.
This is the learned helplessness model of depression.
I think it has strong explanatory power, and yet it is a little odd...

One curious thing about this to me is how acceptance - acknowledging one's inability to change an outcome and consequently accepting it - is therapeutic for depression.
Practically speaking it is the same as feeling helpless, but psychologically speaking it is its direct opposite.

In /The Noonday Demon/ Andrew Solomon describes depression as being too close to the edge of a cliff, overcome by vertigo. He writes:

"Depression is not a lack of agency, that could be freeing. 
Depression is a feeling that all agency has left you when you need it most, and should by rights have it."

One way to frame the difference between acceptance and helplessness is that in acceptance you convince yourself, rightfully or otherwise, that what it is you are helpless against is not so bad.
Often in depression you do not know what you are helpless against, save the pervasive malaise of existing with the condition.
What you dread is the dread itself, just as the fear of panic can escalate a panic attack.
Accepting the dread seems paradoxical - it is an innately intolerable feeling.


Solomon has another quote that is useful here.
"The best way to overcome depression is to dislike it, and not allow yourself to become used to it."

Accepting the dread, accepting your depression can absolutely backfire.
There are things you can and must do to overcome it.
You cannot simply sit back and wait.

Perhaps it is better explained as recognizing that it will pass, and you will get through it.
Useless. That is precisely what depression leaves you unable to believe.

Perhaps it is accepting everything besides your depression, while still hating the feeling of depression, that alleviates it just a little, perhaps just enough that you can begin to believe.
On the other hand, I remember being coached to thank my emotions after identifying them, acceptance being implicit therin.
Thank you for the information, I am taking it into account.

The empowerment lies in accepting the emotion as the bearer of bad news.
It is not about accepting the circumstances, or the misery that the circumstances bring, but accepting the knowledge that the circumstances are unacceptable.
And if you can, in fact fight those circumstances, even if it is only by leaving them behind, this realization may empower you, and get you on your feet again.

I still feel I have not resolved the contradiction.

