:PROPERTIES:
:ID:       497a8d3e-48cf-4e2b-bb52-1be91a174671
:END:
#+title: gamejournal-2025-05-22


Today I played only a few minutes of runescape, and an hour and a half of Immortality.

In runescape I'm at the rogues den.
The place is surprsingly satisfying once you know the route: and it's entirely the opposite of what I expect.
I thought the fun in something like it would be in figuring out the route : but that was unintuitive torture.
Knowing the route and executing it correctly is satisfying - when you do it once or twice in a row.
But it quickly gets old.

Immortality is interesting, It's a relatively passive experience and relaxing as a result.
That said, the actual piecing together of the mystery is not very agency-driven, or curiosity driven.
I'm not often looking for a specific piece of information, and if I were there is little I can do to direct myself towards it.
Nothing at all in fact I think. except to keep looking around.
I'm reminded of Schell's example with top trumps:
you invent gameplay even where gameplay is impossible.
Maybe if I flip the cards over faster I get better results.
Maybe if I follow this character's face I get more backstory scenes.


