:PROPERTIES:
:ID:       ad768b48-b24f-464c-9127-a8c0e20cc4ce
:END:
#+title: freedom-tyranny-agency


I'm reminded of varg vikernes' statement regarding racism that I found so unexpected: that it may not be right but it is instinctive.
That it is harmful to deny that instinct.
Well fuck you varg, how about you follow instinct and go eat fifty thousand marshmallows and get diabetes and die?
Talk to me about the beneficial nature of instinct then.

This isn't rationality, it is intellectual and emotional laziness.

Feeling of agency arises when the instinctive wants and the rational mind are in agreement.
It is easier to forge this feeling by subordinating the rational mind to instinct.
But the downsides of this are fairly obvious.

With immortality's characterization of Law as the destroying, controlling force.
It's wierd how this framing would position the current wave of fascism as the artist.
It is lawless, caring neither for norm nor law, shattering laws while yelling "law and order" like a dadaist performance artist

Yet I think it is obvious from the policing, conformist, tyrannical actions that this is not the case.
The identification of fascism with freedom is, like everything about fascism, surface-level.
Tyranny over the many is, for the few freedom.
But only the few.

But I do see something in the identification freedom with creativity and love
I think the important 
