:PROPERTIES:
:ID:       8881ba2b-f08b-4076-b88f-e87617820521
:END:
#+title: devlog-20250329

I got enno's main mechanic working. I need to test it out to see whether I can really build the fight around it.
That means I need him to use it often.

I need there to be some way for the player to trip him up as well, and I need to do something like AziorghSystem so enno has three things.

Tripping Enno, I think, maybe should only happen when he throws his weapon, so that's another thing to implement.
So it would be like: dodge, dodge, grab & throw.


To be honest, It's not super clear to me how Enno's fight should go and look.
I had some idea before, but I never wrote it down clearly, and it was always a bit iffy.

Here are some notes:
  1. I need Enno to follow up after he knocks you down.
  2. I need Enno to throw his spear, and have its position be exploitable by the player

How about this: when you get knocked down, Enno stabs his spear into the ground,
when you do not, he throws his spear at range, sticking it in the ground.
He has a second spear, and after he throws the second he retrieves the first

His slash can be dodged, but when you close in the footsweep can prevent you from capitalizing, and cannot be dodged.
(I need to signpost that - maybe some dialogue in weaker enemies?)
Footsweeping his slash will lead to a knockback, that can be used to aim him over his spear.
Grabbing him mid-slash can also work if you manage the lift.
Better is to dash to his destination, lift and throw

of course, you can also just batter him until he's stunned and then  throw him over his spear.
The terrain should have a few safe spots to fall, so to maximize your score you direct him there.

One thing I am certain of is that I want Enno to throw his weapon and for it to stick in the ground.
I also need the footsweep to create a small stun and break posture in a direction.
Clockwise or anticlockwise - that will depend on player movement.
I need to add an animation for the throwing.

