:PROPERTIES:
:ID:       49850f2a-9b9e-4150-81ae-68f67e2f3824
:END:
#+title: gamejournal-2025-05-04


It's going to be hard to be consistent in this.
I'm also wondering about the design exercises in the book. I think I need to schedule a time to study, rather than reading it at night. It's not practical.
But fucking when??

Well, today I played a little bit of old school runescape.
The game has a special place in my heart, but it does take a lot of time.
I always leave it and come back to it - maybe next time I lose interest is when I'll start studying for game design.

I took on vorkath. I took him down a bunch of times on my main, but that was years ago and with much better gear.
It's a fun fight, and one where you really acutely feel the sense of progression as you get calmer.
The first few times he throws his rapidfire breath attack at you your vision blurs from the pressure, it's hard to find a path through the poison.
After just a few times, your senses are unaffected: you know how to deal with it.

Progression is the most central kind of joy in runescape, and getting overwhelmed by its bosses at first, the stress involved, the fact that they are very punishing of mistakes, is important to this.
As you learn just enough of each boss' mechanics to stay calm, it feels like a wonderful milestone.
I'm not certain being very punishing is essential: I had this experience with royal titans too, and they were forgiving at our level.




