:PROPERTIES:
:ID:       8e968870-33ab-46ce-a798-a655a312721a
:END:
#+title: the-sacred-workdays

Gravel crunches underfoot and I feel the cold night air.
I've arrived again, and tomorrow I will awaken in the sacred place and get to work with my dear colleagues.
I'm dragging a bag full of prepared meals, to ensure that nothing interrupts the flow we will experience.
In my pocket my phone contains a set of notes, important thoughts that crossed my mind in the last few days.

I have been looking forward to this all week, but as always I've stayed strong.
Never start early, do not disrupt the sanctity of the workdays.
We will take two days to immerse ourselves in our passion, and then return to our ordinary lives of day-to-day maintenance, love, and entertainment.

To take a moment away from the normal and stand at the cutting edge, it's exhilarating.
It is a sure thing that I will awake early with a manic enthusiasm, and sleep well the following night only because of thorough exhaustion.
It's always astonishing how the rigor of hard work makes you appreciate the comfort of rest, and the boredom of rest fills you with energy for work.




