:PROPERTIES:
:ID:       e8cd49f9-d072-4ddc-86be-be3e853d9ded
:END:
#+title: in-the-eye

It isn't light that your eyes speak to you about, it is darkness.
Like an audience awaiting the performance, photoreceptors chatter happily into the silence.
If light were to break through and find them, it is by their silence that their friends would know the show has started.
Now and for a long time still, there is only the absence, a spacious void in which to play.

Behind the eyelids, within the womb, neurons wait for the light.
They join hands and amuse themselves making waves around the stadium.
Your neighbor stands and shouts, they pull you to your feet and so you carry it on!
Like the shadow of a speeding object in the field of view the wavefront moves.
Just like puppies wrestling to hone skills they don't yet need, the neurons in the eye play together and imagine what it is like to see.

Impatient, their activity becomes more vigorous, small, fast waves travel throughout the stadium.
Only at this late phase do they don their team jerseys, bipolar cells of which half cheer for light, and half for dark.


Far behind them, the residents of the brain hear their cheers, broadcast along the optic nerve.
These denizens will never see the performance: the audience itself is the show,
and the show is an orderly movement of waves.

Chaos! The world quivers!
The show begins, the crowd is rapt.
Those hearing the broadcast struggle to comprehend.

Cries the cortical neuron: "Hey! Something moves this way!"
Says another, "Nay, it is nothing."
Some form fast friendships with those who agree with them.
In time, Mind begins to form.

