:PROPERTIES:
:ID:       0c95781f-f459-4b02-80fc-13e2485191cd
:END:
#+title: a-method-for-sanity

Goals create meaning for actions; kicking a ball around with no intent is not fun, playing football is.
Yet focusing on outcomes also creates anxiety.
Picture passing a football between several participants.
Not as exciting as a match, but also less stressful.
This isn't purposeless kicking, you're aiming to get the ball round about there, you kick it, and it does what you expect or it doesn't.
Small, micro-goals which also benefit you in a match.

Being process-oriented is not forgetting about goals, it is keeping smaller goals in mind, smaller victories.
Of course, it is possible to focus on small goals and accumulate a whole which does not lend itself to your larger goals.
In a football match, just passing the ball around will not win the match - you need to enact a strategy.

To be effectively process-driven is to be effectively principle driven: achieving micro-goals in keeping with preestablished principles.
These principles are calculated to work towards the larger, longer-term goal.
Move the ball up the field when possible.
Shoot for the goal when you can.


