:PROPERTIES:
:ID:       d8f6c4bf-e19d-4036-8b88-ab121cfc529c
:END:
#+title: wonderbook-writing-challenge-2
(I'm really not sure if this is the idea with the exercise)


Except in the uppermost part of the forest canopy, it is dark in the rain forest.
Little light penetrates to the forest floor. The uniformity of light, warmth and moisture — in intensity and rhythm — mark the rain forest.
And it is hard to imagine a rain forest dweller that embodies this quality of constancy more than the sloth.
From meters below, the sloth is sometimes described as looking like a clump of decomposing leaves or a lichen-covered bough.
The sloth’s hair is long and shaggy, yet strangely soft. The fur is brown to tan and quite variable in its mottled pattern.
Especially during the wettest times of year, the sloth is tinted green from the algae that thrive on its pelage, which soaks up water like a sponge (Aiello 1985).7

M. Sloth came to visit. He said:

I’m sleepy! I need a good branch for a bed!
I’m quite good at climbing. I know how to swing.

But sleeping’s my favourite, favourite thing!
This branch looks lovely!
I think I’ll sleep here.

Then disaster struck. 

M’s home was near a hotel.
At some point, a tree she depended on for food was likely cut down.
Without enough to eat, M began to starve.
As she grew thinner and thinner, she became sick.
Then a big storm lashed the area, chilling her to the bone.
Too weak to hang on, she likely fell from her tree.

It was able to stand and walk on its hind legs, making it the largest bipedal mammal of all time.
Footprints attributed to M. dating to around 14,000 years old have been found in Argentina, just 40 km from a site where the young Charles Darwin collected the remains of this animal between 1832 and 1833.
These specimens collected by Darwin are historically and scientifically important, but also very fragile meaning that physical access to these specimens has had to be restricted to protect the specimens from further damage.


-----

It is dark under the trees of the rainforest.
Napping there, most of the time, are a great many sloths.
From afar they just look like a bunch of cecomposing plants, with their shaggy, brown and algae-stained fur.

One sloth, being sleepy as sloths are, chose a favourite branch and made it her home.
However, the tree from which this branch came was near a hotel.
A nearby tree, where she gathered most of her food, was cut down.
And the sloth began to starve.
She grew thinner and weaker until she was blown from her tree by a storm.

But then she stood up, and began walking on her hind legs.
She grew to be the largest bipedal mammal of all time, even now 14,000 years later we still have no idea where the hotel came from.



---








--------------

Megatherium was up to 10 times the size of living sloths reaching weights of up to four tonnes (similar to a bull elephant). On its hind legs, M. americanum would have stood a full 3.5 metres (12 feet) tall.

Megatherium americanum is known from Argentina, Uruguay and Bolivia. Fossils of the animals have been found in deposits dating from the Middle Pleistocene (around 400,000 years ago) to the beginning of the Holocene (around 8,000 years ago).

We know that they overlapped with humans in time as Megatherium fossils have been found with cut marks on them, suggesting that these giant sloths were on the menu thousands of years ago.

Despite its magnificent claws, M. was a vegetarian. This has been confirmed through chemical analysis of its teeth which record what it ate during life.

It was able to stand and walk on its hind legs, making it the largest bipedal mammal of all time.

Footprints attributed to M. dating to around 14,000 years old have been found in Argentina, just 40 km from a site where the young Charles Darwin collected the remains of this animal between 1832 and 1833.

These specimens collected by Darwin are historically and scientifically important, but also very fragile meaning that physical access to these specimens has had to be restricted to protect the specimens from further damage.


One day, Mr. Sloth came to visit. He said:

I’m sleepy! I need a good branch for a bed!
I’m quite good at climbing. I know how to swing.

But sleeping’s my favourite, favourite thing!
This branch looks lovely!
I think I’ll sleep here.

And you? Don’t you think that’s a splendid idea?
Oh no, Mr. Sloth! A giraffe’s eating there!


He might think you are lunch and start nibbling your hair!
This branch looks lovely! I think I’ll sleep here.

And you? Don’t you think that’s a splendid idea?
Oh no, Mr. Sloth! There’s a beehive right there!

You’ll never get to sleep with those bees everywhere!
Oh no, Mr. Sloth, that’s a snake over there!

Not a branch! Poor old snake. You gave him quite a scare.
Oh no, Mr. Sloth! There’s a bird squawking there!

You’ll never get to sleep with that noise in the air!

Try to climb one more branch, Mr. Sloth! They all said.

And that branch was just the right one for his bed.

The bird and the snake, the giraffe and each bee were happy to have Mr. Sloth in their tree.



Now we command you, brothers, in the name of our Lord Jesus Christ, that you keep away from any brother who is walking in idleness and not in accord with the tradition that you received from us.
7For you yourselves know how you ought to imitate us, because we were not idle when we were with you,
8nor did we eat anyone’s bread without paying for it, but with toil and labor we worked night and day, that we might not be a burden to any of you.
9It was not because we do not have that right, but to give you in ourselves an example to imitate.
10For even when we were with you, we would give you this command: If anyone is not willing to work, let him not eat.
11For we hear that some among you walk in idleness, not busy at work, but busybodies.
12Now such persons we command and encourage in the Lord Jesus Christ to do their work quietly and to earn their own living.


It is clear that Aquinas and his predecessors had thought a lot about
acediu -are, in effect, experts. Acedia, according to Cassian ‘greatly
troubles monks at noon. It strikes like a recurring fever; it lays the soul
low with sultry fires at regular and fixed intervals.’ Damascene (quoted
by Aquinas) says that media ‘is a kind of oppressive sorrow’ (tristitia
aggravuns) which so depresses a man that he wants to do nothing.”
Acedia is a kind of sorrow over spiritual good; it shrinks from spiritual
good as laborious or irksome to the body.’*Later Aquinas quote Isidore
to the effect that despondency (tristitia) engenders ‘spite, pusillanimity,
bitterness and despair’, while spiritual apathy (media)engenders
‘idleness, drowsiness, verbosity, idle curiosity.’’
