:PROPERTIES:
:ID:       8464e185-6f75-489f-a7df-cbf4d09926fa
:END:
#+title: wonderbook-writing-challenge-3


Dr Samantha Woodridge (POV) character
She picked up a copy of "On the origin of species" just before they left london.
It revitalized her interest in biology, and she has been reading it the whole trip.
She had studied medicine and natural philosophy at the university of Gottingen.
This had required special dispensation and been extremely expensive, but as the sole heir of an immense estate she had this opportunity.
She has given up on finding a husband who will let her maintain her skills and interest.
She is traveling to the americas as a tourist, and hopes to needle her way into lecture halls.

Captain Jeremiah Hobb,
Hot-tempered captain, he has mellowed out since becoming in charge of his own ship.
It might be in part the confidence and autonomy of leadership, that his anger stemmed from insecurity at lower ranks.
He has expensive cargo.
He harbors some doubts about his abilities as a captain, and when these surface his temper comes with them.


Mr. George Summer
A wealthy american lawyer, on his way home.

Captain Jonah Bentham, captian of military vessel escorting Hobb
Calm, collected, severe

Where to start?

Calm morning waters, one or the other captain looking out.
Offers a little time for reflection and set up
May be too slow- no one has any reason to care about these characters yet, so why waste time on their thoughts?

Kraken spotted, bewilderment, wonder and concern.
Immediate tension, but still time for that tension to build with the crescendo of an action scene.
Also gives time to introduce more characters before things really get too wild
Perhaps by Dr woodridge, who is awake early. This allows us to introduce the reader to the POV character right away.

Dr. woodridge awakened from her bed by alarm call
Tension is even more immediate, but may be confusing without any context
frantic pace early makes it hard to introduce characters

The kraken contacts the ship, probing at first
offers building tension and in particular uncertainty - will it actually attack, will it not?
This gives both immediate and less immediate danger for characters to react to in their own ways.

The kraken damages the ship, causing the alarm
tells the reader quickly what the book is about
skips any slow bits, gets on with it quickly

the ship going down, mad scrabble for survival
fast action scene, goo if this is going to be an action packed book
tension will be limited though, because reader has not been introduced to characters and so does not care what happens

drifting in the boat, worried about another attack, flashbacks and speech describe the scene
emphasis not on action but on dread, might be good for a more cerebral book (which I do not think this is)

who sees the kraken first?
A lookout makes the most sense, or a captain.
However that isn't interesting from a narrative perspective.
having one of the captains see the kraken first, or at least be the first whose attenion is called to it,
is a good way to introduce them as a character
we will be adequately introduced to Dr. Woodridge by the POV anyway.


