:PROPERTIES:
:ID:       271b4fb8-cf96-4d49-82ef-db83cc0ce91d
:END:
#+title: homepage
Hey there,

I'm a doctoral student in neuroscience at the EPFL in Lausanne.
I'll be using this space to write about a variety of topics to practice my writing in a low-pressure environment.
Before I was a doctoral student I worked as a programmer for a few years, and I made a lot of progress as a programmer by coding in my spare time without expectations or time pressure.
I'm hoping a blog can lead to the same advances in my writing skills.
Some of my interests on which I'll write include:
 - epistemology
 - software engineering
 - game design
 - psychology

Naturally, I'll also write a fair bit about neuroscience.
In order to keep this feeling like play rather than work I will shy away from my own topic of research (the functioning of the mouse visual cortex).
Instead, I'll branch out into other aresa.

I really value simplicity and accessibility in other people's scientific writing, and want to develop that myself.
As an excercise in that I'll be aiming for a lay audience with these topics.
That's going to be a real challenge, but I do believe that each of these topics is understandable without a university degree.
If you're willing to read that hodgepodge of various content, thanks so much!
Since feedback is important to improve please leave me short reviews of the entries, what you liked, what I could improve, including which specific phrases are not clear or have a poor choice of words.

* Neuroscience
- [[id:84c5b566-23ff-4036-9f58-8b3fcbb1b8b1][serotonin-and-ssris]]
  - [[id:c924678f-5230-48d7-85d7-bf7413e5b2c8][neurotransmission-of-serotonin]]
  - [[id:02504069-e1e7-43c8-a746-43ed27a2f807][serotonin-and-heplessness]]  
  - [[id:9c8961f2-4dbd-4dc9-9cd5-f498abc8afaa][the-serotonin-deficiency-theory]]


* Programming / software engineering
- [[id:d2494e49-8840-4773-8783-6cd586ded217][best-practices-for-programming]]


* Essays
- [[id:94ba5a79-0e68-48b4-b05b-826aa98ca855][lovecraft-and-eldritch-knowledge]]


* creative writing (prompts)
To help me get started with writing consistently, my sister gave me a set of creative writing prompts.

- [[id:245d134a-80ac-4d13-a899-b52465bb36aa][tremble-and-zemble]]
- [[id:b34052c5-b67a-43a7-bed1-2eaa706aaf45][on-the-sonic-habits-of-terra]]
- [[id:dd9bf4ca-f058-4d8d-9377-e1d7586c3cb1][letter-from-ponder]]
